### ISSUE TITLE
Renaming fields in template

### ISSUE THREAD

**Issue by visualcookie** [mzur/kirby-uniform#102]
Hello,

I'm currently setting up my forms with uniform and want to be able to change the fields name in the template.

Currently I have the following output:
```
Name: Dean

Phone:

Companyname: uniquepotion GbR

Companyurl:

Companybranche:

Leistungen: Webdesign, Programmierung, Hosting, Suchmaschinenoptimierung

Budget: 2.000 - 5.000
```

Now I want to be able to change the names of  "companyname" etc.

Do I have to really change their names of their belonging inputs or does this also work on another way. Hope you can help me out. :)

**Comment by mzur** [comment]
You can change the output with a custom [email snippet](https://github.com/mzur/kirby-uniform/wiki/Action:-Email#snippet) like this:

```
Name: <?php echo $form['name'] ?>

Telefon: <?php echo $form['phone'] ?>

Firma: <?php echo $form['companyname'] ?>

...
```

**Comment by visualcookie** [comment]
Awesome, thanks :)
