### ISSUE TITLE
Cannot send session cache limiter - headers already sent 

### ISSUE THREAD

**Issue by mec** [mzur/kirby-uniform#104]
Hey amazing work on this plugin - thank you so much.

Trying to use it on a single page, multilingual site and having this issue.

On the default language (French) everything is fine, when the site switches to English I get this PHP error and in Kirby 2.4.0 it brings the site to a stop!

Any advice would be greatly appreciated.

**Comment by mzur** [comment]
This error happens if PHP already responded with some content when certain functions are called. The classic example is a space at the beginning of the file:
```php
 <?php
?>
```
See [here](http://stackoverflow.com/a/8028979/1796523) for more information.

It's very strange, though, that the behavior changes with the language since the controllers, templates etc. should be the same. Let me know if the information from the StachOverflow link didn't help you.

**Comment by mec** [comment]
It's not that unfortunately. 

If I remove the Uniform code from the controller but leave the function call,  the site is fine, I can't understand what is going on as it only happens on the non-default language...

**Comment by mzur** [comment]
Can you please post the controller and template code? Also, try Kirby 2.3 and see if it works.

**Comment by mec** [comment]
I've rolled back to:

Kirby 2.3 + Uniform 2.2 = same issue
Kirby 2.3 + Uniform 2.1 = same issue

I can remove the form code from the snippet and leave the controller code and get the same issue.

Removing the uniform controller code stops the error. The controller code is:

```
return function( $site, $pages, $page ) {
    $form = uniform('the-contact-form', [
        'required' => [
            'name'  => '',
            'company' => '',
            '_from' => 'email',
            'telephone' => '',
        ],
        'actions' => [
            [
                '_action' => 'email',
                'to'      => 'm.rawlings@example.com',
                'sender'  => 'm.rawlings@example.com',
                'subject' => 'New message from the contact form',
                'service' => 'mailgun',
                'service-options' => array(
                    'key'    => 'key-fdsfdsfsdg',
                    'domain' => 'asgdsdsgsagsdg.mailgun.org'
                  )
            ]
        ]
    ]);
return compact('form');
};
```

These are the actual errors:

```
Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /Volumes/Internal HD 1/MAMP/htdocs/dr_works/site/languages/en.php:28) in /Volumes/Internal HD 1/MAMP/htdocs/dr_works/kirby/toolkit/lib/s.php on line 54

Warning: Cannot modify header information - headers already sent by (output started at /Volumes/Internal HD 1/MAMP/htdocs/dr_works/site/languages/en.php:28) in /Volumes/Internal HD 1/MAMP/htdocs/dr_works/kirby/toolkit/lib/s.php on line 64
```

In Kirby 2.3 with debugging off, you would not see these errors on the site.

Any thoughts would be greatly appreciated!

**Comment by mzur** [comment]
Please show the complete file: `/Volumes/Internal HD 1/MAMP/htdocs/dr_works/site/languages/en.php`

**Comment by mec** [comment]
Amazing - it was the closing ?> in the en.php file - seems to be good now - thank you so much!

**Comment by mzur** [comment]
You're welcome :wink:
