### ISSUE TITLE
Use Kirby's csrf() function

### ISSUE THREAD

**Issue by mzur** [mzur/kirby-uniform#105]
I just stumbled upon the [csrf() helper function](https://getkirby.com/docs/cheatsheet/helpers/csrf). Maybe this can be used instead of the custom token system of Uniform. Thoughts:

- This would make the Uniform ID irrelevant
- Otherwise it could probably be implemented without breaking changes
- Check which Kirby versions support csrf()

**Comment by chbach** [comment]
:+1:
