### ISSUE TITLE
Update the reCAPTCHA guard

### ISSUE THREAD

**Issue by mzur** [mzur/kirby-uniform#106]
Update the reCAPTCHA guard for Uniform v3. @fetzi would you be willing to do this? Else I'd gladly make a PR once the rest of v3 is ready.

You can take a look at the [CalcGuard](https://github.com/mzur/kirby-uniform/blob/b8340ee75b49705b804684da4a95ee75a9300668/src/Guards/CalcGuard.php) for how guards will be implemented in v3.

**Comment by fetzi** [comment]
@mzur I will update the guard, I've created an [issue](https://github.com/fetzi/kirby-uniform-recaptcha/issues/2) in the kirby-uniform-recaptcha repo.

Coming back to this issue when I'm done. Should I also jump to v3?

**Comment by mzur** [comment]
Awesome! There are a few things left until the v3 beta release (see the issues and [this comment](https://github.com/jevets/kirby-form/issues/1#issuecomment-266526655)). If you have any suggestions feel free to join the discussion :wink:
