### ISSUE TITLE
Disable action response

### ISSUE THREAD

**Issue by flogehring** [mzur/kirby-uniform#111]
As a backup for the email action, I've configured a second action to log the entry.
Now the success message always states that the email has been sent and the log entry has been written. I'd like to hide the latter to the user as it might be confusing. I couldn't find an option to disable or change that message, other than changing the language files. Is there a supported way to do this yet?

**Comment by mzur** [comment]
Yes, you can selectively choose the message that should be displayed with the index of the action in the actions array. If the email action is performed first (index `0`) and then the log action (index `1`) you can display the message of the email action with:
```php
<?php echo $form->message(0) ?>
```
