### ISSUE TITLE
Example file upload for version 3

### ISSUE THREAD

**Issue by petertait** [mzur/kirby-uniform#112]
I'm trying to work out how to allow a user to upload a file via a contact form which is then attached to the email.

I can see this is discussed here: https://github.com/mzur/kirby-uniform/issues/73 but I can't find anywhere in the forums or in the docs around how to do this in version 3. Is it still possible?

Thanks for all your amazing work!

**Comment by mzur** [comment]
The upload action of #73 would look like this as a [custom action](https://kirby-uniform.readthedocs.io/en/latest/actions/actions/#custom-actions) in v3 (not tested, my previous advice on file uploads is still relevant):

```php
<?php

namespace Uniform\Actions;

class UploadAction extends Action
{
   public function perform()
   {
      $fields = $this->requireOption('files');
      $target = $this->requireOption('target');

      foreach ($fields as $field) {
         if (!array_key_exists($field, $_FILES)) {
            $this->fail("Field {$field} was not submitted", $field);
         }
      }

      foreach ($fields as $field) {
         move_uploaded_file($_FILES[$field]['tmp_name'], $target.'/'.$_FILES[$field]['name']);
      }
}
```
Usage:
```php
$form->uploadAction([
   'files' => ['file-field'],
   'target' => 'content/'.$page->diruri().'/files',
]);
```
But if you just want to attach the file to an email you don't need to move the file around. All you need is the temporary file `$_FILES[$field]['tmp_name']` and some mailing library of your choice that supports file attachments.

**Comment by krisak** [comment]
> But if you just want to attach the file to an email you don't need to move the file around. All you need is the temporary file $_FILES[$field]['tmp_name'] and some mailing library of your choice that supports file attachments.

What? Could you explain?

I admire the work put into the documentation but maybe you could show how to do simple file sending/saving? I mean most of the people asking about this just need quick contact form with cv attached. 

Ive been through this in version 2 now things have changed and i have to do learning again :D. I spend day making whole website and two days making form :D.

**Comment by krisak** [comment]
OK turns out lot of the problems i have were because of kirby email driver. I slaped together phpmailer driver and it started to work much better.

I am worried about validation of the uploads now but atleast i am sending! :))

**Comment by mzur** [comment]
As I said you need "some mailing library of your choice that supports file attachments". Phpmailer is one of them so you should be good to go with that one :wink: 

There is no documentation for file uploads because there is no official file upload action. This is [planned](https://github.com/mzur/kirby-uniform/issues/113) but until then the "documentation" in the issues must do.
