### ISSUE TITLE
Basic example is not 100% functional

### ISSUE THREAD

**Issue by judbd** [mzur/kirby-uniform#117]
Hi, Thank for this plugin, I try it today and possibly found some error in the basic example:

- Missing ID on labels
- Evocation of an non-existent snippet for error (snippet is showed in advanced example)
- If multiple errors, just one is displayed
- Error displayed on page at first load, ever if the form have not been sent yet

I resolved the last issue with this, don't know if it's the right solution

```
<?php if ($form->success()): ?>
Thank you for your message. We will get back to you soon!
<?php elseif ($form->error($field)): ?>
<?php snippet('uniform/errors', ['form' => $form]) ?>
<?php endif ?>
```

**Comment by mzur** [comment]
Hi, thanks for checking out the example. What you are describing makes me suspect there is something wrong with your Kirby setup. The basic example should be working fine.

> Missing ID on labels

I wanted the example to be as simple to understand as possible. The form works even if the fields have no `id` (and the labels no `for`) so I left them out.

> Evocation of an non-existent snippet for error (snippet is showed in advanced example)

The `uniform/errors` snippet is loaded by uniform through the Kirby extension registry ([here](https://github.com/mzur/kirby-uniform/blob/5c61bf785b7c30d98cad34715117a00b6df79f16/index.php#L7)). As long as you have Uniform installed you can use this snippet even if it doesn't exist in `site/snippets`.

> If multiple errors, just one is displayed

That shouldn't happen. The [snippet](https://github.com/mzur/kirby-uniform/blob/c963c170b3e947b890e2b48e8d06bdc1d39087d0/snippets/errors.php) runs a loop over all fields and prints all errors of a single field. Can you please post your controller and template code so I can check if everything is correct?

> Error displayed on page at first load, ever if the form have not been sent yet

That shouldn't happen either. Let's sort out if your controller and template is correct first. If you just copy and pasted them from the example you don't have to post them here again but make sure the code is exactly the same. What versions of PHP and Kirby do you use?

**Comment by judbd** [comment]
Ok, I think I figured it out, sorry for the inconvenience. All the problems came from my initial misunderstanding of the snippet, so I copied the content of the example snipper in the advanced form and I guess it messed up everything (no loop, wrong control and wrong error count so displayed at load). You can close this issue, sorry.

**Comment by mzur** [comment]
I've added a [note](https://kirby-uniform.readthedocs.io/en/latest/examples/basic/) to the basic example to make this more clear.
