### ISSUE TITLE
Add autoload to panel/index.php as well

### ISSUE THREAD

**Issue by lekkerduidelijk** [mzur/kirby-uniform#120]
I've found out (after bricking a production site) that you need to add `require '..'.DS.'vendor'.DS.'autoload.php';` to panel/index.php as well.
Maybe you should add that to the readme file?

Also: I'm using `kirby` and `panel` as git submodules, so I wonder what happens when a panel update is available... 🤔

**Comment by mzur** [comment]
Thanks for raising this issue, I wasn't aware of it. What about creating a `site/plugins/autoload.php` file and add the `require` there? This should make adding the `require` to both `index.php`'s obsolete and work with updates, too.

**Comment by mzur** [comment]
I've now updated the Composer installation instructions.

**Comment by lekkerduidelijk** [comment]
Top notch @mzur!
