### ISSUE TITLE
Installation of Uniform

### ISSUE THREAD

**Issue by tradedemon** [mzur/kirby-uniform#121]
@mzur 

I'm installing v3 using the traditional method but I get the following error on all my pages that have forms.

_Warning: require(/var/www/public/site/plugins/uniform/vendor/composer/../getkirby/toolkit/bootstrap.php): failed to open stream: No such file or directory in /var/www/public/site/plugins/uniform/vendor/composer/autoload_real.php on line 66

Fatal error: require(): Failed opening required '/var/www/public/site/plugins/uniform/vendor/composer/../getkirby/toolkit/bootstrap.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/public/site/plugins/uniform/vendor/composer/autoload_real.php on line 66_

I was previously using V2 and I simply deleted the V2 files and added the V3 files. I understand that I need to update my forms with the latest forms but I'm not even getting past the installation part.

Thanks
Zee

**Comment by mzur** [comment]
I suspect this has something to do with your setup. Uniform works fine for me with a fresh install of the Plainkit. Which Kirby and PHP versions do you use?

**Comment by lekkerduidelijk** [comment]
I've experienced more or less the same issue (#120) when upgrading from V2 to V3.

You should try to do a `composer require` in the root folder of Kirby or use WPCLI. The traditional method didn't work for me either.

It has something to do with requiring the toolkit and kirby core through composer. The plugin folder doesn't know where to look for it. I couldn't figure it out and used the composer variant in the end.

**Comment by mzur** [comment]
It should definitely work without `composer require`. Can you try to install Uniform with the traditional method in a fresh version of the Plainkit? Does that throw the same error on your system? Maybe it's an issue with an older version of Kirby. Again, which versions of Kirby and PHP do you use?

**Comment by tradedemon** [comment]
Sorry for the late response.

I'm using Kirby 2.3.2 does that help ?

**Comment by mzur** [comment]
I can reproduce the error with that version. I'll see if I can fix this but it should work fine after a Kirby upgrade as well.

**Comment by tradedemon** [comment]
Thanks Mzur, appreciate the rapid turnaround on this. 

Do let me know as soon as you're able to fix it and I'll give it another shot 👍

**Comment by mzur** [comment]
Try the current `master`, it should work now.

**Comment by tradedemon** [comment]
ok trying it now, will let you know shortly.

**Comment by tradedemon** [comment]
Just tested it. Works a treat :)

Thanks 🥇
