### ISSUE TITLE
Use data from page (content) in an e-mail sent with Uniform

### ISSUE THREAD

**Issue by mciszczon** [mzur/kirby-uniform#123]
I want to use some data fetched from ordinary content page and put it into an e-mail that is sent with Uniform's action. The aim is to be able to change the e-mail's content from withing the panel (or by editing the .txt file).

I know that by default I can only use `$data`, which contains the data from the form fields and `$options`. So I tried to pass some data to `$options` and fetch them in the snippet, but with no luck.

This is my controller:

```
return function($site, $pages, $page) {
    $form = uniform('registration-form', [
        'required' => [
            'name'   => '',
            '_from'  => 'email'
        ],
        'actions' => [
            [
                '_action' => 'email',
                'to'      => 'example@mail.com',
                'sender'  => get('_from'),
                'subject' => 'Example',
                'snippet' => 'example-email'
            ],
            [
                '_action' => 'email',
                'to'      => get('_from'),
                'sender'  => 'example@mail.com',
                'subject' => 'Example',
                'snippet' => 'example-email-copy',
                'receive_copy' => false
            ]
        ]
    ]);
  
    if ($form->successful()) go(url());

    return compact('form');
```

I would highly appreciate some help with understanding how to pass that data. Also, I only want to use it with the second action (with the snippet called `example-email-copy`).

**Comment by krisak** [comment]
Is there reason why you want to use uniform 2.3. instead of the newer version 3?

**Comment by mciszczon** [comment]
No, there's no reason for it, I could as well switch to v. 3. Probably the reason is that when I started the project, version 3 was still unreleased.

**Comment by krisak** [comment]
OK. Well i think v3 is a bit better. But this should work the same.

You can add anything to your snippet - in your case 'example-email-copy'
if the global kirby vars are not available you can get them.

https://getkirby.com/docs/cheatsheet/helpers/kirby
https://getkirby.com/docs/cheatsheet/helpers/page

So if you want just to get some page you can do it in the snipped simply like this
` $page = page('mypage');`
And echo stuff like you would with pages.

**Comment by mciszczon** [comment]
Yeah, I just checked and some time ago when I was working on it, the v3 was still unavailable or in an early beta stage. Now I have to make some changes and that's how it goes.
So yeah, the problem for me was that I had no access to these global variables and had no idea how to get to them.

Fetching page with `page('uri')` worked well. I also wanted to get language codes, in which case invoking `kirby()->site()` worked just as well, and then just grabbing `langauge()` from that.

As for the html mail, I have already had it. I just needed to make the e-mail content easier to edit.

Thank you very much for the help!

**Comment by mzur** [comment]
With v2.3 there is the [params option](http://kirby-uniform.readthedocs.io/en/v2.3.0/actions/email/#params) of the email action that allows you to pass data to the snippet. But v3 is the right way to go :wink: Here you can put any data in the [options array](http://kirby-uniform.readthedocs.io/en/v3.0.1/actions/email/#snippet).
