### ISSUE TITLE
CSRF-Token not accepted for AJAX requests

### ISSUE THREAD

**Issue by zvaehn** [mzur/kirby-uniform#124]
Hey there,

i've implemented the ajax-example as shown in the docs: http://kirby-uniform.readthedocs.io/en/latest/examples/ajax/

![image](https://cloud.githubusercontent.com/assets/5555821/23608704/e50e5642-026a-11e7-9f18-5ca3302bd1e9.png)

The kirby()->request()->data():
```
Array
(
    [inputName] => thename
    [inputPhone] => thephone
    [inputDeparture] => thedeparture
    [csrf_token] => UPae8HIHULcT77VI0FuRqTnrWqistUt0T5BvKFMmgobSEijMgVyIRDXU4TPBKx17
    [website] => 
)
```

Raised exeption sais: `Exception: The CSRF token was invalid.`

My javascript is copied 1:1.
The Form-Markup looks like this:

```
<form id="booking-container" class="columns" action="/uniform/tourbooking" method="POST">
...
<input type="text" id="inputPhone" name="inputPhone">
<label for="inputPhone">Phone</label>
...
<?= csrf_field() ?>
<?= honeypot_field() ?>
<input type="submit" value="Submit">
<p id="message"></p>
```

(i also disabled the kirby cache)

Thanks for your help, i become desperate!
Sven

**Comment by mzur** [comment]
Continued in the [forum](https://forum.getkirby.com/t/uniform-csrf-rejection/6858).
