### ISSUE TITLE
Multilingual error-messages

### ISSUE THREAD

**Issue by maxxst** [mzur/kirby-uniform#125]
Would it be helpful to have standard / default error messages for invalid entries too ?

I could offer german :)

```php
l::set('uniform-name-error', 'Please enter your name');
l::set('uniform-mail-error', 'Please enter a valid email address');
l::set('uniform-msg-error', 'Please enter a message');
l::set('uniform-tel-error', 'Please enter a valid phone number');
```

```php
l::set('uniform-name-error', 'Bitte geben Sie Ihren Namen an');
l::set('uniform-mail-error', 'Bitte geben Sie eine gültige E-Mail Adresse an');
l::set('uniform-msg-error', 'Bitte geben Sie eine Nachricht ein');
l::set('uniform-tel-error', 'Bitte geben Sie eine gültige Telefonnummer an');
```

**Comment by mzur** [comment]
I'm not sure about this. All existing language variables are required by some built-in functionality of Uniform. Although the form fields you mentioned are common, none of these are required by Uniform. I'd rather choose not to include that in the default package.
