### ISSUE TITLE
Honeypot gets filled out by 1Password

### ISSUE THREAD

**Issue by zvaehn** [mzur/kirby-uniform#127]
- [How to design your website to work best with 1Password](https://support.1password.com/compatible-website-design/)

**Comment by mzur** [comment]
Can you please suggest a solution or quote the relevant passages from your link?

**Comment by zvaehn** [comment]
I guess disabling the HTML-Autofill should last.

https://support.1password.com/compatible-website-design/#html-autofill-attribute

**Comment by mzur** [comment]
Should be fixed with the current `master`
