### ISSUE TITLE
Adding a select field value to the subject

### ISSUE THREAD

**Issue by fabiovella83** [mzur/kirby-uniform#129]
Is it possible to do something like:
'subject' => $form->value('selection-id')  ' - message from the contact form' ?

**Comment by mzur** [comment]
Yep, it's called [subject templates](https://kirby-uniform.readthedocs.io/en/latest/actions/email/#subject) and works like this: 
```php
'subject' => '{selection-id} - message from the contact form',
```

**Comment by fabiovella83** [comment]
Nice one let me try!

**Comment by fabiovella83** [comment]
I tested it with the example from the documentation 
`'subject' => '{email} - A25 - contact form',`
and I get  **_{email} - A25 - contact form_**  as subject :(
It doesn't seem to pick the template

**Comment by mzur** [comment]
Do you actually have a form field with the name `email`?

**Comment by fabiovella83** [comment]
no I thought I was going to try the example first.
when I tried with the select field id I got the same result though

**Comment by mzur** [comment]
Just to be clear about this: The key to be used as a subject template is the `name` attribute of the form field, not the `id`. So the email form field should look like this:

```html
<input name="email" type="email">
```

And the `selection-id` form field like this:
```html
<select name="selection-id">
  <option value="value1">Value 1</option>
  <option value="value2">Value 2</option>
</select>
```
