### ISSUE TITLE
error installing uniform

### ISSUE THREAD

**Issue by jennygover** [mzur/kirby-uniform#130]
Hello,

I was wondering if you might be able to advise me on an installation of the uniform plugin into an existing kirby site. I have installed the plugin manually by placing the uniform folder in the plugins folder of my site and adding form code as shown, but I get this error when I load the website:

Whoops \ Exception \ ErrorException (E_PARSE)
syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$'

Debug mode points me to this file for the problem: site/plugins/uniform/uniform.php

I am a designer who dabbles in code, so I have clearly made some sort of error implementing the plugin. Any advice would be appreciated!

![screen shot 2017-06-12 at 5 16 30 pm](https://user-images.githubusercontent.com/29387088/27055851-c8d26178-4f93-11e7-80c9-7a31dd7c37b5.png)

**Comment by jennygover** [comment]
Update: It appears to have been the version of PHP -- I was running 5.4 but updated to 5.6 and it appears to run now.

**Comment by mzur** [comment]
Yes you found the correct solution. Kirby supports PHP >= 5.4 but Uniform only supports PHP >= 5.5 (both versions already reached end of life and you shouldn't use them). This is the second time this problem pops up within in a few days so I leave this issue open until I added a note on the version requirement to the docs.
