### ISSUE TITLE
Invalid CSRF

### ISSUE THREAD

**Issue by tradedemon** [mzur/kirby-uniform#131]
Hi mzur,

Sorry to trouble you but on Kirby 2.4.1 and when submitting a form I get:

**"The CSRF token was invalid"**

I checked the form and there seems to be a CSRF token inserted so not sure why it thinks it's invalid.

The dev site is located here.  And it's on that page if you try to fill in the contact form you get the problem.

http://dev.novi.ie/contact

Would you know what the problem might be ?

Thanks
Zee

**Comment by mzur** [comment]
It's probably because the URL is called twice:

![screenshot from 2017-06-20 20-52-26](https://user-images.githubusercontent.com/2457311/27350364-6c172ec4-55fa-11e7-9bf4-eda1643cca03.png)

With the second call the CSRF token is changed and the old one is no longer valid.

**Comment by tradedemon** [comment]
Ah damn, how could I not see that. Awesome you were spot on.

**Comment by guidoferreyra** [comment]
I have the same problem how can I solve this?

**Comment by yoanmalie** [comment]
For folks who came here through a Google search, and because there no solution mentioned above here a tip: **You should ignore the contact page from the cache if you enabled it.**

```
// Ignore page to cache
c::set('cache.ignore', array(
    'contact',
));
```
