### ISSUE TITLE
form field: rules to message is now a many to one relation. Shouldn't it be possible to be a many to many?

### ISSUE THREAD

**Issue by elwin1234** [mzur/kirby-uniform#135]
Hi,

I have a question/proposal about rules and messages. Consider the following example Form object that is used in a registration form:

```
 $form = new Form([
        'name' => [
            'rules' => ['required'],
            'message' => 'Please fill in name',
        ],
        'email' => [
            'rules' => ['required', 'email', 'uniqueUser' => $site],
            'message' => 'Invalid email VS user with email already exists',
        ]
]);
```
`uniqueUser` is a custom validator that I made that checks if the user does not already exists in Kirby.  It is now more convenient to expect different error messages in the following 2 cases:

1. user provides an empty or wrong email
2. user does provide a valid email, but a user with that email already exists in the system 

At the moment kirby-uniform maps all form fields to one single message, whereas it is possible to have more than 1 validator in "rules", right?

**Comment by mzur** [comment]
That's already possible if you use Kirby 2.5. An issue to update the Uniform docs is already open ( #133 ).

**Comment by elwin1234** [comment]
Tnx, great!
