### ISSUE TITLE
Call to a member function old() on null 

### ISSUE THREAD

**Issue by senlin** [mzur/kirby-uniform#146]
As per title.
I have added the plugin (files in site/plugins/uniform folder), the controller and the template example (of the readme.MD). 
Running on localhost, fairly new to Kirby, I think that documentation could be a bit clearer, but that is probably personal preference...
Any ideas?
Thanks!

**Comment by mzur** [comment]
The error message means that the `$form` variable is not initialized. Do your controller and template have the same filenames?

Can you elaborate as to where the documentation could be a bit clearer?

**Comment by senlin** [comment]
> Do your controller and template have the same filenames?

Nope, should they? What should the file name be? How should I call the form in my template then?

> Can you elaborate as to where the documentation could be a bit clearer?

Exactly as per my above questions. In my opinion, it is not clear from the documentation how to add a/the form to a template, how to name things, where to put the other stuff mentioned on the [usage page](http://kirby-uniform.readthedocs.io/en/latest/usage/) of the documentation, why the readme.md file and the usage page have different information, why the readme file setup doesn't work, etc.

**Comment by mzur** [comment]
Then I suggest that you [learn how Kirby templates work](https://getkirby.com/docs/templates) first. In short: the template and controller filenames must match, else the controller is not executed (and the `$form` variable is not initialized).

> it is not clear from the documentation how to add a/the form to a template

Both the readme and the documentation (usage, examples) show how a form should look like in a template. Do you have specific suggestions how to improve this?

> where to put the other stuff mentioned on the usage page of the documentation

Which "other stuff" do you refer to?

> why the readme.md file and the usage page have different information

The readme is intended as a quick start guide and contains only the most minimal information to get you started. The documentation (and usage page) go more in depth.

> why the readme file setup doesn't work

It should work once you set up the template and controller correctly.

**Comment by senlin** [comment]
Thanks for your suggestions
