### ISSUE TITLE
[Improvement] Add logAction Snippet for JSON

### ISSUE THREAD

**Issue by maxxst** [mzur/kirby-uniform#147]
I wanted to show the E-Mail logs readable for my client, so I started thinking about parsing the default logs you create but then I came up with the plan to use JSON log files instead. Then I thought it could be nice for everyone to use JSON log files. So I suggest either adding a snippet or changing the default logs to a json output.

## Snippet file
```php
<?php 
$header = array(
	'date' => date('c'),
	'ip' => Visitor::ip(),
	'userAgent' => Visitor::userAgent(),
);

print( json_encode(array_merge($header, $data)) . "\n"); 
?>
```

## Code in logAction itself
```php
protected function getContent()
{
    $snippet = $this->option('snippet');
    $data = $this->form->data();

    if ($snippet) {
        $content = $this->getSnippet($snippet, [
            'data' => $data,
            'options' => $this->options
        ]);
    } else {

        $header = array(
            'date' => date('c'),
            'ip' =>  Visitor::ip(),
            'userAgent' => Visitor::userAgent(),
        );

        $content = json_encode(array_merge($header, $data));

        $content .= "\n";
    }

    return $content;
}
```

**Comment by mzur** [comment]
Nice idea, this would be a good addition to the log action. But I'd rather stay with the snippet as this does not require changes to the existing action. We can supply the snippet "officially" with Uniform so it's very easy to use.

Do you care to make a pull request? You'd have to add your snippet to the [snippets](https://github.com/mzur/kirby-uniform/tree/master/snippets) directory, then [register it](https://github.com/mzur/kirby-uniform/blob/master/index.php) (e.g. as `uniform/log-json`) and finally mention it in the [documentation](https://github.com/mzur/kirby-uniform/blob/master/docs/actions/log.md).

**Comment by maxxst** [comment]
for consistency: should I move the default behaviour to `uniform/log-default` ? The LogAction itself would then be cleaner :)

**Comment by maxxst** [comment]
do you want me to bump the version or will you do it yourself ?

**Comment by mzur** [comment]
I'll do that. Let me just check your PRs. We can continue the discussion there.
