### ISSUE TITLE
Exception for non-translated Languages.

### ISSUE THREAD

**Issue by zvaehn** [mzur/kirby-uniform#151]
What?
> Uniform does not have a translation for the language 'ru'.

Where?
> `uniform/src/Form.php` Line 95.

Question:
I could simply add an english translation to the plugin languages folder, but it would be great if uniform could have a fallback to the language provided in the config via `c::set('uniform.language', 'en');`
or should that be the expected behavior?

**Comment by mzur** [comment]
Uniform could handle this similar to the [CSRF token mismatch](https://github.com/mzur/kirby-form/blob/860b21c792073d353d1ac554159037767333e1db/src/Form.php#L155-L157) and only throw the exception if Kirby is in debug mode. If not, it falls back to the default language. Care to make a pull request for this?

**Comment by zvaehn** [comment]
I could have a look at it in 1-2 weeks. I am currently very busy. But i can fix this for my current project quick and dirty by adding `ru.php` to the languages folder i think.

**Comment by mzur** [comment]
That would be great. As a quick fix you could also create a link to `en.php` so you don't have to maintain two versions of the file.
