### ISSUE TITLE
UTF8 characters not working in e-mail title

### ISSUE THREAD

**Issue by mciszczon** [mzur/kirby-uniform#152]
I can't get UTF8 characters to work in e-mail title. I'm developing a website in Polish and non of this language letters appear in the title – just gibberish. But there's also problems with other characters, i.e. the em dash.

Everything works fine in the e-mail body—both for simple text and html e-mails.

Example of the title I get: `Piltza 16 â Â dziÄ kujemy za kontakt!`, where it should be `Piltza 16 — dziękujemy za kontakt!`

Using Uniform v3 of course.

**Comment by mzur** [comment]
Can you try to send the email directly with the [`email` helper](https://getkirby.com/docs/cheatsheet/helpers/email) and see if that works? If it doesn't, try to encode the string to UTF-8 with [`str::utf8`](https://github.com/getkirby/toolkit/blob/c9323735246028b22e945f2641e733dc0d774d1a/lib/str.php#L627).

**Comment by mciszczon** [comment]
Sending it with the built-in `email` helper results in the same thing—no UTF8 chars. Encoding it with `str::utf8()` does nothing at all, too.

It's interesting, as the body of the emails work flawlessly. It's only the subjects that are the problem.

**Comment by mzur** [comment]
Then maybe [this](https://stackoverflow.com/a/27648245/1796523) helps. This topic might also have been covered already in the Kirby forum. Finally, you could try to use a mailing library lihe [PHPMailer](https://forum.getkirby.com/t/contact-form-with-phpmailer-uniform/6469) which probably does this stuff automatically for you.

**Comment by mciszczon** [comment]
@mzur Thanks for the heads up! I was initially thinking that it's an issue with your plugin itself, and thus didn't even try to think of it outside that scope. Dumb me, I guess.

I used your first recommendation, and encoding the subject with `iconv_mime_encode()` did the trick for me. Using PHPMailer would do the trick too, I believe, but it's more hassle than needed as for my needs.

Thank you for all the quick replies! You were really helpful :)
