### ISSUE TITLE
How to send file via Email with Uniform.

### ISSUE THREAD

**Issue by juliencharette** [mzur/kirby-uniform#153]
Is there a guide on how to send and email with uploaded pdf as attachment? I do not wish to save the uploaded file in the filesystem, only send it via email. Thanks.

**Comment by mzur** [comment]
There is no proper guide but there are a few threads in the forum that might help you (like [this one](https://forum.getkirby.com/t/contact-form-with-phpmailer-uniform/6469) and [this one](https://forum.getkirby.com/t/send-emails-using-phpmailer/2570)). Basically you have to implement a new email service that uses PHPMailer and sends an uploaded file as email attachment. The only thing you tell Uniform is to use the PHPMailer email service and to validate the uploaded file (like in [this example](http://kirby-uniform.readthedocs.io/en/latest/actions/upload/)).

If you have more questions on this topic, please open a new thread in the forum and we can continue the discussion there. I'd like to keep the GitHub issues to feature requests and bug reports only.
