### ISSUE TITLE
composer setup fails. no 4.x release

### ISSUE THREAD

**Issue by bnomei** [mzur/kirby-uniform#160]
`composer require mzur/kirby-uniform:^4.0`

>  [InvalidArgumentException]
  Could not find package mzur/kirby-uniform in a version matching ^4.0

**Comment by mzur** [comment]
Yeah, there is no 4.0 release yet. I'm still waiting for the Kirby guys to resolve my pull request.

**Comment by bnomei** [comment]
i see but...
`composer require mzur/kirby-uniform:"dev-master as 4.0.0"` fails as well.

> Problem 1
    - Installation request for mzur/kirby-uniform dev-master as 4.0.0 -> satisfiable by mzur/kirby-uniform[dev-master].
    - mzur/kirby-uniform dev-master requires getkirby/cms dev-develop || >=3.0.0-beta-4.2 -> no matching package found.

for my plugins i am using
```json
"require": {
        "getkirby/cms": "dev-master as 3.0.0"
},
```
https://github.com/bnomei/kirby3-autoid/blob/master/composer.json#L28

**Comment by bnomei** [comment]
and
```json
"minimum-stability": "beta"
```

**Comment by mzur** [comment]
I've never seen a syntax like `dev-master as 4.0.0` before. Can you point me to where it is documented? As far as I know you have to use just `dev-master` instead.

**Comment by bnomei** [comment]
its a shorthand, usefull in terminal when calling `require`, for an (alias)[https://getcomposer.org/doc/articles/aliases.md].
the `dev-master as 3.0.0` is for the getkirby/cms requirement. and yes for uniform i could just use `dev-master` but i wanted to hint that using `3.x` will not work.

**Comment by bnomei** [comment]
i tried using the zip and call composer there but requirements kirby-form and kirby-flash also have the same setup. i can not get it to work with the devkit oneway or the other.

**Comment by bnomei** [comment]
solved it: using `dev-master` for `getkirby/cms` and `kirby-uniform` does work with my and @omz13 plugins.

```json
"require": {
    "getkirby/cms": "dev-master",
    "bnomei/kirby3-feed": "^1.0",
    "omz13/kirby3-xmlsitemap": "^0.4.4",
    "mzur/kirby-uniform": "dev-master"
  }
```
