### ISSUE TITLE
sessionStoreAction() not saving values after successful redirect

### ISSUE THREAD

**Issue by carstengrimm** [mzur/kirby-uniform#162]
I've built a kirby v3-beta form which should be processed later on so i am using the sessionStoreAction()

Most of the code is basically adjusted from the docs and the whole validation as well as

``` $form->success() ``` stuff is working properly.

After my whole validator / field declaration i am using the following code:

```
    if($kirby->request()->is('POST')){
        $form->sessionStoreAction();
        if($form->success()){
            go($page->children()->visible()->find($kirby->session()->get('session-store')->data('payment')));
        }
    }
```

As you can see on the redirection, it's already accessing the session-store "Payment" value...

```
    $uid = $page->children()->visible()->pluck('uid');

//....
            'payment' => [
                'rules' => ['required', 'in' => [$uid]],
                'message' => 'Bitte wählen Sie eine Zahlungsoption aus.', ' Sie haben eine ungültige Zahlungsmethode gewählt.'
            ]
```

The redirect is actually working, so for the time being there is any information saved.

When being in the redirected page i am trying to access the session info to output the contents

```
dump(kirby()->session());
// or any other i could know of
```

and the whilest some information (csrf) is saved, the data itself is missing...

```
[csrf] => c13b7131b08dc0177076652c709837eba70e6383f4fbce6105f4ef64e0172c8a
                    [session-store] => Array
                        (
                        )

```

I haven't actually found out if it gets overwritten somewhere else.. I am using other $kirby->session->set('other-keys', $values) pairs however the session-store data is only used by the code above.

I am overlooking a few things here?

**Comment by mzur** [comment]
Can you try to manually set some variable in the session (`$kirby->session()->set($key, $value)`) and see if this is available on the redirect page? I'd like to rule out Kirby's new session implementation as error source.

**Comment by carstengrimm** [comment]
I have already set other session variables and they seem to stick 

(Cart Array, and some other test variables while investigating the issue)

Am 10. Oktober 2018 18:34:55 MESZ schrieb Martin Zurowietz <notifications@github.com>:

**Comment by mzur** [comment]
Apparently the new session implementation uses JSON to store session data. It does not allow for serialization of the whole Form object as it was possible before. The tests did not pick this up because I had to disable the real session store since it was not possible to use it in tests. I'm not very happy with their new session implementation to be honest. I'll open an issue at the Kirby repo.

**Comment by carstengrimm** [comment]
thanks.

is there any alternative solution i could use to access all values and save them via ``` $kirby->session()->set() ``` for the time being or will this affect the whole thing - with validation, $form->success() and so on?

**Comment by mzur** [comment]
You can do it a lot simpler than that. The SessionStoreAction really doesn't do much:
```php
if ($kirby->request()->is('POST')) {
   // This performs validation (sets success) and the HoneypotGuard.
   $form->guard();
   if ($form->success()) {
      $kirby->session()->set('user-data', $form->data());
      go(/*...*/);
   }
}
```
The only difference is that the object stored in the session is a simple array and not the whole form object. So to access a field you need to call e.g. `$kirby->session()->get('user-data')['firstname']`.

**Comment by mzur** [comment]
The session store action should work again with Kirby 3 beta 7. Please reopen if you still encounter any issues with this version.
