### ISSUE TITLE
E-Mail sends even though all rules are not applied

### ISSUE THREAD

**Issue by carstengrimm** [mzur/kirby-uniform#163]
Using the latest dev-master version I've build a form from github with basically everything copy paste from the github page

```
$form = new Form([
    'name' => [
        'rules' => ['required'],
        'message' => 'Bitte geben Sie Ihren Vor- und Zunamen ein',
    ],
    'company' => [],
    'email' => [
       'rules' => ['required', 'email'],
        'message' => 'Bitte geben Sie Ihre E-Mail ein',
    ],
    'text' => [],
 ]);

 if ($kirby->request()->is('POST')) {
    $form->emailAction([
       'to' => 'me@example.com',
       'from' => 'info@example.com',
    ]);
 }

 return compact('form');
```

and even though my values are empty an email is being send - even though the error template is showing after submission. I assume this is not intended?

**Comment by mzur** [comment]
Works for me:tm: with the latest `master` of Kirby 3. Looks like the CSRF token is not stored in your session. Do you still do something special to the session (thinking of #162) and accidentally delete the token?

**Comment by carstengrimm** [comment]
weird thing, it seems like it is working now without any further change....
not sure what was "stuck" there...

**Comment by mzur** [comment]
They should probably check `$session->has('csrf')`, too, before using `hash_equals` to handle cases like these more gracefully. Sounds like a good pull request for Kirby if you'd like to fix this :wink:  Closing as resolved.

**Comment by carstengrimm** [comment]
On a sidenote i just noticed the error i mentioned occurs when the connection is not secured (https)

**Comment by mzur** [comment]
Maybe Kirby's session cookie is HTTPS only. This way the session won't work for insecure connections. If this is an issue for you, you'll have to discuss this with the Kirby guys.
