### ISSUE TITLE
Class 'Uniform\Form' not found

### ISSUE THREAD

**Issue by baernty** [mzur/kirby-uniform#165]
hello,
i tried the plugin but get Class 'Uniform\Form' not found error. 
copied the files into site/plugins/uniform/ but it seems like autoloader is not working correctly? 

do you have a glue?
thank you!

**Comment by mzur** [comment]
Do you use Kirby 2 or Kirby 3?

**Comment by baernty** [comment]
Thanks for the reply.
I use Kirby 2.5.12

**Comment by mzur** [comment]
Then you probably installed the `master` branch of Uniform, which is already meant for Kirby 3. Please try it again with [this version](https://github.com/mzur/kirby-uniform/archive/kirby-2.zip).

I noticed that the download link in the readme of the `kirby-2` branch is still pointing to the `master` branch. I'll fix that.

**Comment by baernty** [comment]
Thanks a lot, that helped :)
