### ISSUE TITLE
problems with kirby rc-4

### ISSUE THREAD

**Issue by bnomei** [mzur/kirby-uniform#167]
when using uniform with rc-4 i am getting errors...
```
            $form = new Form([
                'text' => [
                    'rules' => ['required'],
                    // 'message' => 'Suchbegriff',
                ],
            ]);
```

```
Call to undefined method Kirby\Http\Request::postData()
```

`Jevets\Kirby\Form__construct…/vendor/mzur/kirby-uniform/src/Form.php 73`
`Kirby\Toolkit\Facade__callStatic…/vendor/mzur/kirby-form/src/Form.php 103`

**Comment by mzur** [comment]
You seem to have kirby-form for Kirby 2 running. I just published the stable versions for Kirby 3. Please retry with `mzur/kirby-uniform:^4.0`.

**Comment by bnomei** [comment]
worked. thanks.
