### ISSUE TITLE
Bug: #2354a17 crashed plugin using zip install method

### ISSUE THREAD

**Issue by jschopplich** [mzur/kirby-uniform#171]
Hello Martin,

when using your great plugin the old fashioned way, my K3 installation stopped working and throws:
`Fatal error: Uncaught Error: Class 'ComposerAutoloaderInite75dd71623baa0bafc37ab0f4ea53383' not found in [...]/kirby-uniform/vendor/autoload.php:7`

I hunted the bug down to https://github.com/mzur/kirby-uniform/commit/9181ef36167f2ad7e5c6d57fc0ea92d9c0a3b745 from 6 days ago — the Composer class in `vendor/autoload.php` updated without updating the respective scripts in `vendor/composer/*.php`.

Reverting `ComposerAutoloaderInite75dd71623baa0bafc37ab0f4ea53383` back to `ComposerAutoloaderInit8361aa1cb8819bca1a482f61df7f91cc` fixed it for me.

**Comment by mzur** [comment]
Thanks for the bug report. This should be fixed in [v4.0.1](https://github.com/mzur/kirby-uniform/releases/tag/v4.0.1). There is a reason why Composer files usually are not included in the package but that's the way Kirby 3 works...

**Comment by jschopplich** [comment]
Yeah, Composer... But I do like the option to just downloaded zip for quick testing. It's old-school but efficient. Thanks for this!
