### ISSUE TITLE
False page redirect although `withoutRedirect` set

### ISSUE THREAD

**Issue by johannschopplich** [mzur/kirby-uniform#172]
I used your AJAX-example. But every time I submit the form, I am redirected to the page I set in the form's `action`. I can't stop it from redirecting – it somehow happens apart from the JavaScript part.

It gets even more weird.

The router always redirects me to the error page respectively the template + content will be called. If I visit the same URL in the browser everything works, but (wrongly) being redirect by the Router outputs the error page instead of the regular content. 

Now I tried setting up a page just for "mailing" and called it `mailer`. The forms's action is pointed there as well as the route listenes to this URL. But the same redirect happens and again the error page is thrown. Nevertheless I have test content in the `mailer` template.

I dont' get it. Maybe you're able to track this down?...

**Comment by mzur** [comment]
This sounds like your JavaScript isn't working properly. Take a look at the [example](https://kirby-uniform.readthedocs.io/en/latest/examples/ajax/). It uses `e.preventDefault()` in the `submit` function, which prevents the form from making a regular `POST` request. If this function is not called, you get the default form behavior that would be exactly what you describe. Please show your route, template and JavaScript.

**Comment by jschopplich** [comment]
Thank you for your fast response.

My form:
```html
<form id="newsletter-form" action="<?= page('newsletter-mailer')->url() ?>" method="post" data-validate>
  <!--
  [...]
  -->
  <button type="submit" class="button is-link">Eintragen</button>
</form>
```

ECMAScript part:
```js
document.querySelector('#newsletter-form').addEventListener('submit', function (event) {
  event.preventDefault()

  var request = new XMLHttpRequest()
  request.onload = function () {
    if (xhr.status >= 200 && xhr.status < 300) {
      console.log('Success!', xhr)
      document.querySelector('.newsletter-notification').classList.remove('is-hidden')
    } else {
      console.log('The request failed!')
    }
  }

  request.open('POST', event.target.action)
  request.send(new FormData(event.target))
})
```

Finally the (reduced) route:
```php
[
  [
    'pattern' => 'newsletter-mailer',
    'method' => 'POST',
    'action' => function () {
      $form = new \Uniform\Form([
        'salutation' => [
          'rules' => ['required'],
          'message' => 'Bitte wählen Sie einen Wert aus.'
        ],
        /*
        [...]
        */
        'terms' => [
          'rules' => ['required'],
          'message' => 'Dieses Feld ist erforderlich.'
        ]
      ]);
    
      // Perform validation and execute guards
      $form->withoutFlashing()
           ->withoutRedirect()
           ->guard();

      if (!$form->success()) {
        // Return validation errors
        return Response::json($form->errors(), 400);
      }

      // If validation and guards passed, execute the action
      $form->emailAction([
        'from' => $form->data('email'),
        'to' => 'uniform@mzur.rocks',
        'subject' => '...',
        'template' => 'newsletter',
        'data' => [
          'salutation' => $form->data('salutation'),
          [...]
          'email' => $form->data('email')
        ]
      ]);
  
      if (!$form->success()) {
          // This should not happen and is our fault
          return Response::json($form->errors(), 500);
      }

      // Return code 200 on success
    }
  ]
]
```
