### ISSUE TITLE
Bug: Amazon SES service cc and bcc fields missing

### ISSUE THREAD

**Issue by marcobiedermann** [mzur/kirby-uniform#173]
I've refactored my form to use from default Kirby mail form to uniform using Amazon SES service.
The service was running before refactoring and I haven't changed anything on that end.
As soon as I try to send a post request I get

> The mail could not be sent!

Unfortunately no further hints.
My action looks like this:
```php
$form
  ->emailAction([
    'to'      => 'TO_ADDRESS',
    'from'    => 'FROM_ADDRESS',
    'subject' => 'SUBJECT',
    'service' => 'amazon',
    'service-options' => [
      'key'    => getenv('SES_KEY'),
      'secret' => getenv('SES_SECRET'),
      'host'   => getenv('SES_HOST'),
    ],
  ]);
```

I also hardcoded all credentials, so sourcing those from `.env` has no side effects.

Any help / ideas / advice?

**Comment by marcobiedermann** [comment]
I found the solution to my problem.
AWS requires to set `cc` and `bcc` fields. Unfortunately you can not pass those options to your plugin.

**Comment by mzur** [comment]
How does your `amazon` email service look like? You should be able to pass `cc` and `bcc` on to the service using the `service-options`.

**Comment by marcobiedermann** [comment]
What do you mean with

> How does your amazon email service look like?

I'm using amazon SES service and use it as defined above:

```php
'service' => 'amazon',
    'service-options' => [
      'key'    => getenv('SES_KEY'),
      'secret' => getenv('SES_SECRET'),
      'host'   => getenv('SES_HOST'),
    ],
```

Unfortunately you can not pass `cc` and `bcc` to `service-options`. Also according to the docs this should be on the same level as `to` and `from` and not part of `service-options `https://getkirby.com/docs/guide/emails#simple

When submitting the form I get

```
object(Email) {
 …
 ["cc"]=> NULL ["bcc"]=> NULL
}
```

**Comment by mzur** [comment]
Are you using Kirby 2 or Kirby 3? Email services were a thing in Kirby 2 but no longer exist in Kirby 3. However, you link to the docs of Kirby 3.

**Comment by marcobiedermann** [comment]
I am using Kirby 2 but just linked to V3 docs since there is no direct link to V2 docs available.

**Comment by mzur** [comment]
Ok, you have two options:

1. Implement a [custom](https://kirby-uniform.readthedocs.io/en/kirby-2/actions/actions/#custom-actions) email action that also sets `cc` and `bcc` ([here](https://github.com/mzur/kirby-uniform/blob/cca2da5862d00bd7e744d8a9aff181c82ff93790/src/Actions/EmailAction.php#L39-L47)).

2. Implement a custom `amazon` email service that applies `cc` and `bcc` from the `service-options`. You can find the default `amazon` email service in `kirby/toolkit/lib/email.php`.

**Comment by mzur** [comment]
Please reopen if this is still relevant.
