### ISSUE TITLE
Add version in code

### ISSUE THREAD

**Issue by bvdputte** [mzur/kirby-uniform#175]
Hey @mzur ,

Would it possible to add the plugin version in the code (or readme) somewhere?
When you download to the plugin manually, atm there's no way to figure out which version we're looking at. This is difficult to match with the documentation later on.

PS: thanks for this great plugin!

**Comment by bvdputte** [comment]
I'm no composer user tbh.

Is there a way to _read_ the version from a composer.json (as we have with package.json)? Or how does composer keep track of the versions?

**Comment by mzur** [comment]
Composer installs the packages in a `vendor` directory. In this directory it creates the file `vendor/composer/installed.json` which contains information about all installed packages and their versions. But you can simply run `composer info` which gives you a list of all installed packages and their versions, too.

**Comment by mzur** [comment]
Please reopen if this is still relevant.
