### ISSUE TITLE
Problem with Ajax Example in docs

### ISSUE THREAD

**Issue by ldanielswakman** [mzur/kirby-uniform#176]
While implementing an (AJAX-based) Uniform on a (Kirby 3) website, I noticed that the example code in the docs produces server errors. It's about the responses on L33, L44 and (I presume) missing response on L48). It occurs here:
https://github.com/mzur/kirby-uniform/blob/v3.5.0/docs/examples/ajax.md

Comparing to an older version, there should be a `$code` variable defined on various places, with a response being sent at the end `return Response::json(['success' => $form->success(), 'errors' => $form->errors(), 'code' => $code]);`. Is that correct? Or am I seeing something wrong?

**Comment by mzur** [comment]
I just checked the AJAX example with a fresh install of the Kirby 3 Plainkit. It works fine. What server errors do you get? Any error messages would be helpful.

**Comment by mzur** [comment]
Please reopen if this is still relevant.

**Comment by ldanielswakman** [comment]
Srry had lost this thread — but just saw that the current latest version seems correct; in the original link I posted I was looking at v.3.5.0 apparently https://github.com/mzur/kirby-uniform/blob/v3.5.0/docs/examples/ajax.md
