### ISSUE TITLE
Form submission on redirected domain

### ISSUE THREAD

**Issue by MichaelPrecel** [mzur/kirby-uniform#177]
Hey there,

Thanks for the great plugin. 

I have a form operating on a website that redirects users from the .com to the .com.au domain. When I test the submission of the form on the original .com domain, the email is sent, but when I try it from the redirected site at .com.au, the page refreshes without any actual form submission or email sent. 

Not sure if this is a bug, or if there is a feature that can resolve this? Any help if much appreciated!

**Comment by mzur** [comment]
This is most likely a session issue. Uniform stores information in the session to follow the post/redirect/get pattern. The session of a user is identified using a session cookie. But cookies are only valid for a single domain. After the redirect to the other domain, the user gets a new session and the old one is lost.

How exactly do you do the redirect? And why do you need the redirect?

**Comment by MichaelPrecel** [comment]
Thanks for your response @mzur. 

The redirect is set up so that when visitors first enter the .com site, they are instantly redirected (301) to the .com.au domain. However, the .com domain is the primary domain in cPanel. The redirect is required basically because the client wants to ensure the .com.au domain is used (I guess it confirms location, etc). 

Are there any ways around this? Would an alias as opposed to a redirect make a difference?

Thanks again.

**Comment by mzur** [comment]
So if I understand that correct it is not like this (like I first thought):
1. User enters site
2. User submits form
3. User is redirected

But like this:
1. User enters site
2. User is redirected
3. User submits form

Is that right? In this case, make sure that the form `action` points to the correct URL (.com.au and not .com).

**Comment by MichaelPrecel** [comment]
Hey @mzur, thanks again for your reply.

You're correct in your second explanation there. Sorry, but I'm not sure where to specify the form action. Controller code is as below:

`<?php

use Uniform\Form;

return function ($kirby)
{
  $form = new Form([
    'name' => [
      'rules' => ['required'],
      'message' => 'Please enter your name',
    ],
    'email' => [
      'rules' => ['required', 'email'],
      'message' => 'Please enter a valid email address',
    ],
    'phone' => [
      'rules' => ['required', 'num'],
      'message' => 'Please enter a valid phone number',
    ],
    'role' => [],
    'comments' => [
      'rules' => ['required'],
      'message' => 'Please provide a short intro'
    ],
  ]);

  if ($kirby->request()->is('POST')) {
    $form->emailAction([
        'to' => 'info@website.com.au',
        'from' => 'info@website.com.au',
        'subject' => 'New website enquiry',
    ])
    ->logAction([
      'file' => $kirby->roots()->site().'/registrations.log',
    ])
    ->emailAction([
      // Send the success email to the email address of the submitter.
      'to' => $form->data('email'),
      'from' => 'info@website.com.au',
      // Set replyTo manually, else it would be set to the value of 'email'.
      'replyTo' => 'info@website.com.au',
      'subject' => 'Thanks for your email!',
      // Use a template for the email body (see below).
      'template' => 'success',
    ]);

    if ($form->success()) {
      go('success');
    }
  }

  return compact('form');
};`

And for some reason the emails that come through have all value pairs from the form except for the 'email', which is obviously the crucial one. Any suggestions there?

I've been testing heaps in succession and now I'm getting an invalid CSRF token error — could this just be because of pressing submit so many times in a relatively short timeframe?

Sorry to spam you with a list of questions. I've been through the docs but am finding these issues difficult to resolve. Thanks again.

**Comment by mzur** [comment]
> Sorry, but I'm not sure where to specify the form action. 

This is the action attribute of the form element in the template: `<form action="xyz">` How does that look in your template?

> And for some reason the emails that come through have all value pairs from the form except for the 'email', which is obviously the crucial one.

The email is not included by default because the email that you receive has "replyTo" set to the email address of the user who submitted the form. If you want to include the email in the form body, too, you have to use an email template for that. You can use the [`uniform-default`](https://github.com/mzur/kirby-uniform/blob/6a3597692771c5777c8a567e36e162e23cb5410d/templates/emails/default.php) template which is provided by Uniform.

> I've been testing heaps in succession and now I'm getting an invalid CSRF token error — could this just be because of pressing submit so many times in a relatively short timeframe?

It might be. For example if you double click on submit and send two requests with the same data, the first one invalidates the token and the second one fails because of a token mismatch.

**Comment by mzur** [comment]
Please reopen if this is still relevant.

**Comment by MichaelPrecel** [comment]
Thanks very much @mzur. The setup has been resolved and is working based on your advice above!
