### ISSUE TITLE
fails to load email template

### ISSUE THREAD

**Issue by bnomei** [mzur/kirby-uniform#178]
i created a regular kirby 3 email template at `site/templates/emails/contact-customer.php`

but wehn using the `emailAction` neither 
```
'template' => 'contact-customer',
```
nor 
```
'template' => 'emails/contact-customer',
```
will work but an error is returned. i am using ajax to make a post request to a custom route following along with your [ajax example](https://kirby-uniform.readthedocs.io/en/latest/examples/ajax/).

> {"Uniform\\Actions\\EmailAction":["Es ist ein Fehler beim Senden aufgetreten: The email template \"contact-customer\" cannot be found"]}

**Comment by mzur** [comment]
I can't reproduce this with a fresh install of the Plainkit and Uniform v4.0.1. Can you please give some more details?

**Comment by bnomei** [comment]
in essence its your ajax example. i just added `'template' => 'emails/contact-customer',` instead of using subject and body. i am not providing data since your plugin [does that](https://github.com/mzur/kirby-uniform/blob/master/src/Actions/EmailAction.php#L53).

but it seems the file must be two files named `contact-customer.html.php` and `contact-customer.text.php` to make it work. just having `contact-customer.php` fails with error above. so maybe its kirbys core fault?

**Comment by mzur** [comment]
> in essence its your ajax example. i just added 'template' => 'contact-customer', instead of using subject and body.

This worked for me with the current `master` of the Plainkit. The `html.php` and `text.php` templates are supposed to be optional. Maybe this is a bug in Kirby which has been fixed in a newer version?

**Comment by bnomei** [comment]
i am using 3.0.3. but thanks for checking with a plainkit.
i will be using html/text version anyway so i do not care so much as to spend any more time debugging this now. maybe some other day.
