### ISSUE TITLE
ajax example in docs missing response 200

### ISSUE THREAD

**Issue by bnomei** [mzur/kirby-uniform#179]
https://kirby-uniform.readthedocs.io/en/latest/examples/ajax/

it says in the docs
```
// Return code 200 on success.
```

but thats the last line of code in the route and there is no
```
return Response::json([], 200);
```

which seems to be needed to make it work.

**Comment by mzur** [comment]
Are you sure? I think code 200 is returned by default.

**Comment by bnomei** [comment]
i am getting 404 if route does not return anything.

**Comment by mzur** [comment]
You are right. I fixed that.
