### ISSUE TITLE
can not override data send to email

### ISSUE THREAD

**Issue by bnomei** [mzur/kirby-uniform#180]
i wanted to reformat a value from the formdata and forward that value to the email using the same var name (client uses ids to build custom email). my email templates are just oneliners. i am using logicless email templates and multilang setup (parsing mjml generated html with some mustache tags). 

problem is that the array_merge order overrides my reformatted var. i will use a different varname for now but i just wanted to let you know. maybe its not really intended.

```
$form->emailAction([
                    'to' => option('email.presets.contact-form.from'),
                    'from' => option('email.presets.contact-form.from'),
                    'subject' => trim($form->data('subject')),
                    'template' => 'contact-client',
                   'data' => ['roomname' => ucfirst('roomname')],
                ]);
```

https://github.com/mzur/kirby-uniform/blob/master/src/Actions/EmailAction.php#L47
```
        if (array_key_exists('data', $params)) {
            $params['data'] = array_merge($params['data'], $this->form->data());  // <-- here
        } else {
            $params['data'] = $this->form->data();
        }
```

**Comment by mzur** [comment]
This override is intended. If you want to change form data, you can either do it in the template or before the email action is invoked (using `$form->data('mykey', 'mynewvalue')`).

**Comment by bnomei** [comment]
oh my. a setter function. how could i miss that. thanks so much for you quick repsonse, saved me a lot of hassle.
