### ISSUE TITLE
How to get unique session storage?

### ISSUE THREAD

**Issue by Cuboctaedro** [mzur/kirby-uniform#181]
I am trying to use multiple forms in one page as in the docs example. What I can not find is how to retrieve the session storage value.
If I do this:
`$contactForm = new Form([/* rules */], 'contact-form');`
Then all these return false:
```
$kirby->session()->get('contact-form');
$kirby->session()->get('kirby-uniform.contact-form');
$kirby->session()->get('mzur/kirby-uniform.contact-form');
```
How can I check for `contact-form` ?

**Comment by mzur** [comment]
The form uses [kirby-flash](https://github.com/mzur/kirby-flash) and [kirby-form](https://github.com/mzur/kirby-form) under the hood. You can get the flash instance like this:
```php
use Jevets\Kirby\Flash;

$flash = new Flash('contact-form');
```

Then you can get the form data or form errors like this:
```php
use Jevets\Kirby\Form;

$data = $flash->get(Form::FLASH_KEY_DATA);
$errors = $flash->get(Form::FLASH_KEY_ERRORS);
```

That said, why do you need the session storage value? You can get the form data and errors through the form object after all.

**Comment by Cuboctaedro** [comment]
I have a page with three forms defined in the controller like this:

```
$contactForm = new Form([/* rules */], 'contact-form');
$bookingForm = new Form([/* rules */], 'booking-form');
$newsletterForm = new Form([/* rules */], 'newsletter-form');
```

Then I am trying to implement what is described here: 
https://kirby-uniform.readthedocs.io/en/latest/answers/#i-have-multiple-static-forms-on-one-page-when-one-fails-the-error-messages-are-also-displayed-for-the-other-forms-why

```
if ($kirby->request()->is('POST') ) {
       if (/*  $newsletterform is submitted */) {
           /*  $newsletterform actions */;
        } elseif ( /*  $bookingform is submitted */ ) {
             /*  $bookingform actions */;
        } elseif ( /*  $contactform is submitted */) {
             /*  $contactform actions */;
        }
}
```

What I am missing is how to test which form is submitted.

**Comment by mzur** [comment]
You can do this with an additional hidden form field for each form:
```html
<input type="hidden" name="form" value="contact-form">
```
Then check in the controller which form has been submitted:
```php
if (get('form') === 'contact-form' {
   // ...
} elseif (get('form') === 'booking-form') {
   // ...
}
```

**Comment by Cuboctaedro** [comment]
Thank you, this works fine.
