### ISSUE TITLE
Composer Installation to custom directory

### ISSUE THREAD

**Issue by Kreativschnittstelle** [mzur/kirby-uniform#183]
Hey there,

I am having an issue with the composer installation of the plugin. It seems not to get moved to "kirby-plugin-path" in my composer.json. In another plugin a missing tag was the problem, have a look here:
https://github.com/TimOetting/kirby-builder/issues/108

Thanks
Matthias

**Comment by mzur** [comment]
If you are using Composer, this plugin should be installed to the `vendor` directory and not to the Kirby plugin directory. You should be able to use it either way.

**Comment by mzur** [comment]
Please reopen if this is still relevant.
