### ISSUE TITLE
reCAPTCHA v3

### ISSUE THREAD

**Issue by lareusmedia** [mzur/kirby-uniform#184]
Is there already a possible simple way to implement the reCAPTCHA v3 from google?

The Link in the docs contains an old extra-plugin for kirby2

**Comment by mzur** [comment]
> Is there already a possible simple way to implement the reCAPTCHA v3 from google?

The simplest way would probably be to port the old plugin to Kirby 3 and then update it to work with reCAPTCHA v3. Else you would need to write a new plugin or, if you don't want to share your code, just a new guard class. The old plugin should still work fine with Uniform v4.

> The Link in the docs contains an old extra-plugin for kirby2

You're right, the plugin no longer works with Kirby 3. I've removed it from the docs for Uniform v4.

**Comment by illycz** [comment]
Any chance that you integrate reCAPTCHA v3 to actual Uniform?

**Comment by lareusmedia** [comment]
I integrated it by myself A few weeks ago. If you want I could send a pull request

**Comment by illycz** [comment]
Are you integrate it as custom Guard? Yes it would be nice...

**Comment by mzur** [comment]
@lareusmedia You can send a PR to the original Uniform reCAPTCHA [repo](https://github.com/fetzi/kirby-uniform-recaptcha). Once there is a version compatible with Kirby 3, I'll add the notice to the docs again.

**Comment by snalld** [comment]
Any word on this? @lareusmedia do you have a fork where you integrated reCAPTCHA? Need this for a project

**Comment by lareusmedia** [comment]
@snalld Thats not that easy to be honest, because we built the "big solution" around the uniform plugin, including googles recaptcha v3 AND considering the european DSGVO (GDPR). So we created a script which loads the recaptcha scripts (and all others, e.g.: google maps, jameda, newsletter2go etc.) only if you accept the conditions. Otherwise you see a placeholder image of a deactivated form :)

**Comment by mzur** [comment]
Please reopen if this is still relevant.

**Comment by illycz** [comment]
@snalld do you have a solution? Thanks

**Comment by snalld** [comment]
@illycz never found a solution… sorry

**Comment by eXpl0it3r** [comment]
I've implemented a new reCAPTCHA v2 for Kirby 3 and am happy to look into providing support for reCAPTCHA v3.

https://github.com/eXpl0it3r/kirby-uniform-recaptcha

**Comment by mzur** [comment]
@eXpl0it3r Neat! I've added the plugin to the docs again.

**Comment by illycz** [comment]
@eXpl0it3r support for reCAPTCHA v3 would be awesome!

**Comment by eXpl0it3r** [comment]
@illycz can you check out my proposal that you see linked here ^ 

Want to hear some opinions before I implement it 🙂

**Comment by illycz** [comment]
@eXpl0it3r give me some time, I'm bussy :)
