### ISSUE TITLE
Multilingual emails

### ISSUE THREAD

**Issue by illycz** [mzur/kirby-uniform#188]
I have multilingual site.
I filled email templates from panel fields.
When I try to send forms from different languages I still get content from default language.

Any suggestions?

Thanks

**Comment by mzur** [comment]
Uniform just takes the language that was selected by Kirby. How did you implement your form, via AJAX with a route as endpoint or as a regular controller?

**Comment by illycz** [comment]
Via ajax: https://kirby-uniform.readthedocs.io/en/latest/examples/ajax/

**Comment by mzur** [comment]
Then you may have to declare different routes for the different languages (see [here](https://getkirby.com/docs/guide/routing#multi-language-setup)).

**Comment by illycz** [comment]
So I need for every form and every language separate route?
If now I have `/book-demo` route, I need also `/de/book-demo`, `/es/book-demo` etc. and use it conditionally in form action?

And when I specify route language, translations strings and panel fields should work so I can reuse same action function for this multilingual routes?

Sorry for my stupid questions.

**Comment by mzur** [comment]
Yes that should be correct.

**Comment by illycz** [comment]
I'm lost, I tried this:

```
[
    'pattern' => '/career',
    'language' => 'en',
    'method' => 'POST',
    'action' => formCareer()
],
[
    'pattern' => '/de/career',
    'language' => 'de',
    'method' => 'POST',
    'action' => formCareer()
],
```

Where `formCareer` is function defined in congih.php before return. But I get 500. I'm not developer so I don't understand deeply php stuffs. I don't want define same action function for same form routes if you understand what I mean.

Thanks

**Comment by mzur** [comment]
You can do it like this:
```php
$formCareer = function () {
   // stuff
};
```
And then assign the function like this: `'action' => $formCareer`.

**Comment by illycz** [comment]
When I'm trying add /de/karriere as form action and route, everything look ok, but email not comes.

Any suggestion why? Default language working as expected...

**Comment by illycz** [comment]
OK, it looks when language setting is defined in route, it's working as prefix. So you must set route `karriere` and language to `de` and than add to action `/de/karriere`. Now emails comes, but I have still only default content in email content. I'm using `<?= page('career')->email()->kirbytext() ?>`. Is it correct?

**Comment by mzur** [comment]
That should be correct. But since this seems to be a general Kirby issue and not a bug of this plugin, I suggest that you ask for help in the official [forum](https://forum.getkirby.com/). There are more people there who can help you out with this issue.

**Comment by illycz** [comment]
Sure, I create issue: https://forum.getkirby.com/t/uniform-in-multilingual-setup-within-ajax-support/15944

When I will have solution I also paste it here and close issue. Thanks

**Comment by mzur** [comment]
Please reopen if this is still relevant.
