### ISSUE TITLE
Page redirect on submission

### ISSUE THREAD

**Issue by MichaelPrecel** [mzur/kirby-uniform#190]
Hi @mzur,

Fantastic plugin, thank you!

I have an issue with an AJAX setup using whereby the json response is being loaded into the browser or otherwise the page redirects to home. 

This only seems to happen when coming from a different page and navigating to the contact page. I am using Barba.js, so not sure if that is interfering with the normal behaviour? 

Eg, using the AJAX example provided in the docs, if I come from _www.mysite.com/about_, and navigate to _www.mysite.com/contact_ and then submit the form, either _return Response::json([], 200)_ loads as a page with an empty array '[]' with the url _mysite.com/contact_ or if I remove that line of code, the page redirects to the home page. I can't seem to disable this redirect — any ideas?

**Comment by mzur** [comment]
Since the issue you describe is not a bug in Uniform, please post this in the [forum](https://forum.getkirby.com/). You get better help there.

**Comment by MichaelPrecel** [comment]
Thanks @mzur, the problem was with BarbaJS not loading in my JS and so ignoring the preventDefault on the form. Not a Uniform problem! Thanks anyway.
