### ISSUE TITLE
support csrf_token submission as query param

### ISSUE THREAD

**Issue by bnomei** [mzur/kirby-uniform#191]
took me quiet a while to track this down... please mention in the docs that when the global debug is set to true the CSRF check will always throw the `The CSRF token was invalid.` exception.

kirby-form/src/Form.php line 158

**Comment by bnomei** [comment]
nevermind. the problem was that i did send the csrf_token as query param not in request body.

**Comment by bnomei** [comment]
maybe you could verify if using the global `get()` helper is good enough and allow query param submission.
```
// current
$token = $app->request()->body()->get(self::CSRF_FIELD);
// suggested
$token = get(self::CSRF_FIELD);
```

**Comment by bnomei** [comment]
i ran into this when using fetch instead of xmlhttprequest
```js
var request = new XMLHttpRequest();
request.open('POST', this.$refs.form.action);
request.onload = onload;
request.send(new FormData(this.$refs.form));

fetch(this.$refs.form.action, {
    method: 'POST',
    body: new FormData(this.$refs.form)
})
```

**Comment by mzur** [comment]
I don't think this is the correct way to do a POST request:
```js
fetch(this.$refs.form.action + '?' + params.toString(), {method: 'POST'})
```
In a POST request, data is sent in the request body and not as query parameters. Query parameters are for GET requests. This is why Uniform only processes the body of the request.

**Comment by bnomei** [comment]
you are right. i initially tried to 'GET' the request. if uniform (or the kirby-form) only accepts POST data then i have no complains that the query params are not supported.
