### ISSUE TITLE
Class 'Kirby' not found

### ISSUE THREAD

**Issue by rzschoch** [mzur/kirby-uniform#192]
I am about to implement a simple form.

This is my controller:

```php
use Uniform\Form;

return function ($kirby, $page) {
  $form = new Form([
    'name' => [
      'rules' => ['required'],
      'message' => (string) $page->form_name_error()
    ],
    'email' => [
      'rules' => ['required', 'email'],
      'message' => (string) $page->form_email_error()
    ],
    'message' => [
      'rules' => ['required'],
      'message' => (string) $page->form_message_error()
    ],
    'privacy' => [
      'rules' => ['required'],
      'message' => (string) $page->form_privacy_error()
    ],
    'captcha' => [
      'rules' => ['required', 'num'],
      'message' => (string) $page->form_captcha_error()
    ],
  ]);

  if ($kirby->request()->is('POST') and get('submit') === 'contact-form') {
    $form->calcGuard()->emailAction([
      'to' => (string) $page->form_to(),
      'from' => (string) $page->form_from(),
      'subject' => (string) $page->form_subject(),
      'template' => 'contact-form'
    ]);

    if ($form->success()) {
      go(page('contact/form-sent')->url());
    }
  }

  return compact('form');
};

```

After submitting, the following issue occurs (in site/plugins/uniform/vendor/mzur/kirby-form/src/Form.php):

`Class 'Jevets\Kirby\Validator' not found` on line 169

This is the line responsible for the error:

`$validator = new Validator($this->data, $this->rules, $this->messages);`

I have already added the import for the class Validator without success:

```php
namespace Jevets\Kirby;

use Kirby\Cms\App;
use Kirby\Toolkit\I18n;
use Jevets\Kirby\Flash;
use Jevets\Kirby\FormInterface;
use Jevets\Kirby\Validator;
use Jevets\Kirby\Exceptions\TokenMismatchException;
```

My Kirby version: 3.3.4

Thanks for your help and the plugin!

**Comment by mzur** [comment]
How did you install Uniform? Does the file `site/plugins/uniform/vendor/mzur/kirby-form/src/Validator.php` exist?

**Comment by rzschoch** [comment]
Thanks for pointing me to the missing Validator.php!

I did the installation manually and downloaded uniform from here: https://github.com/mzur/kirby-uniform/archive/master.zip

With your gitignore in place, many files are not in my repository and therefore not uploaded during my deployment.

```
# site/plugins/uniform/.gitignore
vendor/*
!vendor/composer
!vendor/mzur/kirby-form
!vendor/mzur/kirby-flash
!vendor/autoload.php
*.sublime-*
```
In the next step I would simply delete this file. Or would you have a better suggestion?

**Comment by rzschoch** [comment]
I ended up modifying the .gitignore to only exclude the composer subfolder:

`/vendor/composer/*`

**Comment by mzur** [comment]
I would recommend that you use Composer for the installation: `composer require mzur/kirby-uniform:^4.0`. The solution with the ZIP file is rather hacky and only mentioned because it is the usual way this is done with Kirby.

**Comment by rzschoch** [comment]
Is this possible without kirby being installed via composer? Unfortunately, I didn’t find the right source folder for executing `composer require mzur/kirby-uniform:^4.0`. After installing uniform via composer I currently get this error `Class 'Uniform\Form' not found`.

**Comment by rzschoch** [comment]
Ok, I decided against the composer installation for now. I too see the benefits (simple updates) but this would lead to some more adjustments in my build pipeline. For that, the advantages are too small for me.

Thanks for your time and help here.

**Comment by mzur** [comment]
You should be able to use Composer even if Kirby wasn't installed with it. You execute the command in the root directory and Composer installs the packages in a new `vendor` directory. The plugin should work right away as Kirby automatically picks up and activates packages installed this way.

**Comment by rzschoch** [comment]
Unfortunately, this is not working. After executing the command in the root directory the installation is finished successfully (new vendor folder in root). But I do get a fatal error now:

`Fatal error: Uncaught Error: Class 'Kirby' not found in /vendor/mzur/kirby-uniform/config.php:3`

**Comment by rzschoch** [comment]
I have to add: The installation is working fine when kirby is intalled via composer, too.

**Comment by mzur** [comment]
Your're right, Kirby [exclusively uses](https://github.com/getkirby/plainkit/blob/4f5ea9b91801c282f7dd23af889f22c5e2964f5a/kirby/bootstrap.php#L13-L18) the installation in the root directory if it is present. I'm not sure if it's intentional that Kirby is not loaded in that case (as they say "additional packages" there) but that's how it is.
