### ISSUE TITLE
Webhook to Slack executing but still throwing error

### ISSUE THREAD

**Issue by ldanielswakman** [mzur/kirby-uniform#193]
Hello, I have a problem with a Slack Webhook implementation with Uniform (Kirby 3), that gets called via AJAX (See config route code below) . The issue is that the webhook does execute, in the sense that a message arrives in Slack, but the AJAX call fails: it doesn't even return the `500` response as JSON, but the call actually fails and throws a console error:
![image](https://user-images.githubusercontent.com/4538367/75692979-a32a3400-5ca6-11ea-8671-ca19eaf16d29.png)

When I add a `.fail(function(response) { ... })`, it shows the error:
`"Undefined property: Kirby\Http\Remote::$error"` (line 54)

```php
// inside AJAX route in config.php

$slack_data = [
   "blocks" => [
    [
      "type" => "section",
      "text" => [
        "type" =>"mrkdwn",
        "text" =>"New message"
      ]
    ],
    [...],
    [
      "type" => "context",
      "elements" => [
        [
          "type" => "mrkdwn",
          "text" => "*Source*: Contact Form"
        ]
      ]
    ]
  ]
];

$form->webhookAction([
  'url' => $slack_webhook_url,
  'json' => true,
  'params' => [
    'method' => 'POST',
    'data' => $slack_data
  ]
]);
// ...
```

Any idea how this might be solved?

**Comment by mzur** [comment]
Please try the code proposed in #194 and report back if it works.

**Comment by ldanielswakman** [comment]
Just tried the changes and worked like a charm! They actually resolved the error; currently, the webhook call succeeds without problems and returns a `200`  👍
