### ISSUE TITLE
'receive-copy' or confirmation email

### ISSUE THREAD

**Issue by psntr** [mzur/kirby-uniform#195]
Hi,

I'm new to this plugin and manage to send email with the AJAX examples. The only thing I'm struggling with is the 'receive-copy' that seems not to work. I'm trying to send the user a sort of confirmation email.

As I'm using the AJAX examples, in my config.php I have the following:

```
// If validation and guards passed, execute the action.
                $form->emailAction(
                    [
                        'to' => 'myemail@company.com',
                        'from' => 'myemail@company.com',
                        'subject' => '{{subject}} - from {{name}}',
                        'template' => 'simple',
                        'receive-copy' => true
                    ]
                );
```

Alternatively I've try this too but no luck:

 ```
$form->emailAction(
                    [
                        'to' => 'myemail@company.com',
                        'from' => 'myemail@company.com',
                        'subject' => '{{subject}} - from {{name}}',
                        'template' => 'simple',
                    ],
                    [
                        'to' => '{{email}}',
                        'from' => 'myemail@company.com',
                        'subject' => 'Your message',
                        'template' => 'copy',
                    ],
                );
```

I still receive the email at the "to" address but not on the input email from the form, also nothing in the spam box. Am I missing something?

**Comment by psntr** [comment]
Ok my bad, as it turns out the receive is working I just didn't add it in my contact form template…

Nevertheless, I'm still wondering if there is a way to send a custom email to the user email? Like my second example (that doesn't work yet) use the template 'copy'.

**Comment by mzur** [comment]
The template strings like `{{email}}` only work for the subject. To get the email from the input you can use `get('email')`. Other than that your second example should work.

**Comment by psntr** [comment]
Thank you for your fast reply. 
I just tried the `get('email')` instead of the `{{email}}`. But no luck. 

```
$form->emailAction(
                  [
                      'to' => 'myemail@company.com',
                       'from' => 'myemail@company.com',
                       'subject' => '{{subject}} - from {{name}}',
                       'template' => 'simple',
                   ],
                   [
                       'to' => get('email'),
                       'from' => 'myemail@company.com',
                       'subject' => 'Your message',
                       'template' => 'copy',
                   ],
```

Maybe that would work if it would be inside the controller instead of routing method? At the moment I'll just use the `receive-copy` method.

**Comment by mzur** [comment]
Ah, sorry, you also have to call `emailAction` for each instance where you want to send an email:

```
->emailAction(...simple...)->emailAction(...copy...)
```

**Comment by psntr** [comment]
Thank you very much, I can confirmed that this works like a charm!
