### ISSUE TITLE
Log Action with Ajax and CALC guard

### ISSUE THREAD

**Issue by dev-ofty** [mzur/kirby-uniform#198]
Hi there,

I'm facing an issue with the form where I am using **AJAX** to send the form with the **CALC captcha** solution. I wanted to add the **LOG** method as well. But by adding it to my current config, that happen:

- Whether or not the **captcha** result is right or wrong, the page send a `200 success` and do a hard refresh.
- The Log works and register right or wrong message.

I have this in config.php:
```php
'routes' => [
        [
            'pattern' => 'contact',
            'language' => '*',
            'method' => 'POST',
            'action' => function () {
                $form = new \Uniform\Form([
                    'name' => [],
                    'email' => [
                        'rules' => ['required', 'email'],
                        'message' => 'Please enter a valid email address',
                    ],
                    'tel' => [],
                    'subject' => [],
                    'text' => [
                        'rules' => ['required'],
                        'message' => 'Please enter a message',
                    ],
                    'captcha' => [
                        'rules' => ['required', 'num'],
                        'message' => 'Please fill in the captcha field',
                    ],
                ]);
                // Perform validation and execute guards.
                $form->withoutFlashing()
                    ->withoutRedirect()
                    ->guard();

                if (!$form->success()) {
                    // Return validation errors.
                    return Response::json($form->errors(), 400);
                }
                // If validation and guards passed, execute the action.
                $form->emailAction(
                    [
                        'to' => 'info@mydomain.com',
                        'from' => 'info@mydomain.com',
                        'subject' => 'New {{subject}} - from {{name}}',
                        'template' => 'simple',
                        'receive-copy' => false
                    ]
                )->emailAction(
                    [
                        'to' => get('email'),
                        'from' => 'info@mydomain.com',
                        'subject' => 'Your {{subject}} — mydomain.com',
                        'template' => 'copy',
                        'receive-copy' => false
                    ]
                )->logAction(
                    [
                        'file' => kirby()->roots()->site() . '/messages.log',
                    ]
                );
                if (!$form->success()) {
                    // This should not happen and is our fault.
                    return Response::json($form->errors(), 500);
                } 
                    // Return code 200 on success.
                    return Response::json([], 200);
                
            }
        ],
…
```

By removing the `logAction` the hard refresh is not happening but the result is also 200 success. Any ideas why it's happening?

**Comment by dev-ofty** [comment]
Ok now  I figured out the Captcha issue:

```
// Perform validation and execute guards.
                $form->withoutFlashing()
                    ->withoutRedirect()
                    ->calcGuard() // Forgot to add that
                    ->guard();
```
 but the logAction still perform a hard refresh. Where should it be placed to avoid that?

**Comment by mzur** [comment]
What do you mean by hard refresh? If you are using AJAX, the page shouldn't refresh no matter what happens in the route action.

**Comment by dev-ofty** [comment]
Thanks for your reply. I am sorry what I meant was that the page reload when using:
`->logAction(
                    [
                        'file' => kirby()->roots()->site() . '/messages.log',
                    ]
                );`
by removing it, everything works as expected. So I wonder if ->logAction() works in the route config. Or I placed it in the wrong place?

**Comment by mzur** [comment]
The page refresh is still caused by your JavaScript code and should not depend on what happens in the route action. Maybe a `preventDefault()` is missing somewhere?

**Comment by dev-ofty** [comment]
That's really odd. I have this in my javascript:
`const form = document.querySelector('form');
        const message_error = document.getElementById('message');
        const message_success = document.getElementById('success');
        var fields = {};
        form.querySelectorAll('[name]').forEach(function (field) {
          fields[field.name] = field;
        });
        // Displays all error messages and adds 'error' classes to the form fields with
        // failed validation.
        var handleError = function (response) {
          var errors = [];
          for (var key in response) {
            if (!response.hasOwnProperty(key)) continue;
            if (fields.hasOwnProperty(key)) fields[key].classList.add('error');
            Array.prototype.push.apply(errors, response[key]);
          }
          message_error.innerHTML = errors.join('<br>');
        }
        var onload = function (e) {
          if (e.target.status === 200) {
            form.classList.add('sent')
            message_success.scrollIntoView({ behavior: "smooth", block: "center", inline: "start" });
            setTimeout(function () {
              form.reset();
            }, 1000);
            setTimeout(function () {
              form.classList.remove('sent')
              form.classList.remove('error')
            }, 6000);
          } else {
            handleError(JSON.parse(e.target.response));
            form.classList.add('error');
          }
        };
        var submit = function (e) {
          e.preventDefault();
          var request = new XMLHttpRequest();
          request.open('POST', e.target.action);
          request.onload = onload;
          request.send(new FormData(e.target));
          // Remove all 'error' classes of a possible previously failed validation.
          for (var key in fields) {
            if (!fields.hasOwnProperty(key)) continue;
            fields[key].classList.remove('error');
          }

        };
        form.addEventListener('submit', submit);`

And it's working properly at the moment. I'm having hard time figuring out why it's reloading the page when using `->logAction` in config.php

**Comment by mzur** [comment]
Can you spot any differences in the requests (in the network console) with or without the log action?

**Comment by dev-ofty** [comment]
Just checked, they are the same, same weigh, same status response and resquests.

**Comment by dev-ofty** [comment]
Also tried to remove the CalcCaptcha and other guard. But as soon as there is` ->logAction` the page reload after submit…

**Comment by dev-ofty** [comment]
Ok big big mistake on my side! The code was actually always working, I am so sorry wasting your time. 

I was actually working with a hot reload module, and seems to be the problem, once, I try without the hot reloading module it works as expected!

Again so sorry about that, thank you very much for your help!
