### ISSUE TITLE
Uniform installed via composer and copied to remote, Kirby fails to run

### ISSUE THREAD

**Issue by renestalder** [mzur/kirby-uniform#202]
I had this error, a bit similar to #192. My CI system is installing all dependencies via composer and then deploys the CMS via SSH to a remote.

On the remote, the CMS failed due to Uniform. This is the output of the error log:

```
[07-Jan-2021 10:39:54] PHP Fatal error:  Uncaught Error: Class 'Kirby' not found in /home/project/public_html/cms.staging/vendor/mzur/kirby-uniform/config.php:3
Stack trace:
#0 /home/project/public_html/cms.staging/vendor/composer/autoload_real.php(71): require()
#1 /home/project/public_html/cms.staging/vendor/composer/autoload_real.php(61): composerRequire8aad1bf71df2248c1b544aa0fc675e39('513c89d6408d266...', '/home/project/...')
#2 /home/project/public_html/cms.staging/vendor/autoload.php(7): ComposerAutoloaderInit8aad1bf71df2248c1b544aa0fc675e39::getLoader()
#3 /home/project/public_html/cms.staging/kirby/bootstrap.php(21): include('/home/project/...')
#4 /home/project/public_html/cms.staging/index.php(3): require('/home/project/...')
```

I then installed composer on the remote server (even though I already get all dependencies during the build in my CI system), ran `composer install` (which yields "Nothing to install... generating optimized autoload files") and with this, the site worked.

Yet, I don't exactly understand what Uniform is doing differently to other plugins that makes the CMS break without composer installed (supposing that the missing composer installation was the issue). And I can't expect that all remotes ever will have composer installed or come with the possibility to install it.

Any input on this?

**Comment by mzur** [comment]
It's not the missing Composer installation but apparrently the need to regenerate the autoload files. I can't say why this is, though. You could compare `vendor/autoload.php` and the files in `vendor/composer/` before and after you ran `composer install` on the remote to see what changes fixed the issue.

**Comment by renestalder** [comment]
You're right. It's something with autoloader as in frequent deploys I saw that the composer install is always required even though all dependencies are already available. I temporarily deactivated the plugin on that particular website to work around the issue (and because I anyway changed the code earlier due to Uniform's CRFS check, [see question in the forum](https://forum.getkirby.com/t/uniform-deactivate-csrf-check-for-headless-usecases/20643/2).

I'll debug it as proposed by you as soon I have a bit of time to reactivate the plugin and check those autoload files.

**Comment by mzur** [comment]
Please reopen when you know more.
