### ISSUE TITLE
Usage with virtual pages

### ISSUE THREAD

**Issue by renestalder** [mzur/kirby-uniform#203]
I tried to create a virtual page which renders a template with a form in it. Turns out the `$form` instance isn't available in the template when it is rendered that way.

Testing by rendering the template directly, not as a virtual page, it works without issues.

Any trick to make that $form instance available in a virtual page?

**Comment by mzur** [comment]
I'm not familiar with virtual pages and haven't worked with Kirby for some time. I think it's best you ask the experts in the Kirby forum. If you're convinced that this is a bug to be fixed by Uniform, come back here and we can work on resolving this bug.

**Comment by renestalder** [comment]
Alright, will do so. Thanks for your answer.

**Comment by nilshoerrmann** [comment]
It might be an idea to have a look at routes and how to pass data to the controller: 
https://getkirby.com/docs/guide/routing#pass-data-to-controller

Like initializing your virtual page and the form instance in the route, passing the form instance to the render function. But it's just a guess how it might work.

**Comment by mzur** [comment]
Please reopen if you can't resolve this in the forum.
