### ISSUE TITLE
Setting empty array to form->data()

### ISSUE THREAD

**Issue by periode** [mzur/kirby-uniform#207]
Hello,

I'm having an issue setting a form field to an empty array. I'm not an expert in PHP so it might be something on my end, but I have a form which gets submitted with a number of empty array fields. For instance:

`var_dump($form->data('titles') //-- returns arr(3){'', '', ''}`

I remove all the empty fields with:

`$pruned = array_filter($form->data('titles'), 'trim'); //-- returns arr(0);`

which results in an empty array. I then want to set this empty array as the value of `titles[]` with:

`$form->data('titles', $pruned); //-- still returns(3){'', '', ''}`

And the expected behavior would be for `$form->data('titles')` to return an empty array.

Thanks for your time and for the project!

**Comment by mzur** [comment]
This was a bug in kirby-form. I fixed it in kirby-form [v2.1.2](https://github.com/mzur/kirby-form/releases/tag/v2.1.2) and Uniform [v4.3.1](https://github.com/mzur/kirby-uniform/releases/tag/v4.3.1).

**Comment by periode** [comment]
Confirmed that it works, thanks for the quick reply!
