### ISSUE TITLE
Mail templates print `_data` & `_options`, too

### ISSUE THREAD

**Issue by S1SYPHOS** [mzur/kirby-uniform#210]
Hey there,
title says it: when using either one of your example templates, the resulting email includes `_data` & `_options`, which is undesired, obviously .. used a fresh 3.5.7.1 starter to confirm!

Thanks for this great plugin, it's one of **the best** out there for Kirby!

Cheers
S1SYPHOS

**Comment by mzur** [comment]
Fixed in v4.3.3, thanks!

**Comment by S1SYPHOS** [comment]
Thank you!

Glad to help
