### ISSUE TITLE
Fatal error: "Session is currently read-only because it was accessed via an old session token"

### ISSUE THREAD

**Issue by nilshoerrmann** [mzur/kirby-uniform#213]
For some reasons, it's possible that Kirby sessions are locked and read-only. Uniform does not anticipate this when flashing content and thus throws an fatal `error.session.readonly` in `kirby/src/Session/Session.php`, line 537:

> Session "1234567890.9e345rtz8f4a4cce24tw" is currently read-only because it was accessed via an old session token

Stack trace:

```
#0 …/kirby/src/Session/SessionData.php(201): Kirby\Session\Session->prepareForWriting()
#1 …/kirby/src/Session/Session.php(327): Kirby\Session\SessionData->pull('_flash', Array)
#2 …/site/plugins/uniform/vendor/mzur/kirby-flash/src/Flash.php(39): Kirby\Session\Session->__call('pull', Array)
#3 …/site/plugins/uniform/vendor/mzur/kirby-flash/src/Flash.php(50): Jevets\Kirby\Flash->__construct('_flash')
#4 …/site/plugins/uniform/vendor/mzur/kirby-form/src/Form.php(87): Jevets\Kirby\Flash::getInstance()
#5 …/site/plugins/uniform/src/Form.php(73): Jevets\Kirby\Form->__construct(Array, NULL)
#6 …/site/controllers/login.php(7): Uniform\Form->__construct(Array)
#7 [internal function]: Kirby\Cms\App->{closure}(Object(Kirby\Cms\App))
#8 …/kirby/src/Toolkit/Controller.php(49): Closure->call(Object(Kirby\Cms\App), Object(Kirby\Cms\App))
#9 …/kirby/src/Cms/App.php(460): Kirby\Toolkit\Controller->call(Object(Kirby\Cms\App), Array)
#10 …/kirby/src/Cms/Page.php(349): Kirby\Cms\App->controller('login', Array, 'html')
#11 …/kirby/src/Cms/Page.php(1178): Kirby\Cms\Page->controller(Array, 'html')
#12 …/kirby/src/Cms/App.php(687): Kirby\Cms\Page->render()
#13 …/kirby/src/Cms/App.php(1040): Kirby\Cms\App->io(Object(Kirby\Cms\Page))
#14 …/public/index.php(70): Kirby\Cms\App->render()
#15 {main}
```

I see that this error is caused by `kirby-flash` but my guess is that the actual error handling has to be done inside Uniform itself. That's why I'm posting here.

### Expected behaviour

I'd expected Uniform to catch this error, setting the form to failed and providing an error message.

**Comment by mzur** [comment]
Can you reproduce this error, i.e. test the behavior? It's a little hard to handle this properly because the session data is required to repopulate the form. Users should probably not end up with an empty form if this happens. What we could do instead is to get the data read-only and continue to handle the request. Ideally, the CSRF token of the session would be invalid, too, and the user would see an appropriate error message. Only the session wouldn't be flushed. But it's hard to do anything here if it can't be reproduced/tested.

**Comment by nilshoerrmann** [comment]
I have an install where I can reproduce this.

**Comment by mzur** [comment]
And what steps do you perform to reproduce it?

**Comment by nilshoerrmann** [comment]
That‘s not easy to tell, yet – I’ve been discussing this issue with Lukas Bestle over the last weeks. It has to do with multiple instances of the same site in different tabs/windows and performing login and logout actions in the frontend and panel.

**Comment by nilshoerrmann** [comment]
Sorry for sounding so mysterious – I havn‘t got a reduced test case so far.

**Comment by mzur** [comment]
No worries. Please let me know when you have a reliable way to reproduce this.

**Comment by nilshoerrmann** [comment]
I thought about this a bit more: So we are actually not that much interested in the original issue that was causing the locked session for us right now, instead we are looking for a way to create this error repeatedly to catch and handle it, am I right?

**Comment by nilshoerrmann** [comment]
I just got feedback from Lukas that there might be a fix in the Kirby core for this issue. So let's wait for now.

**Comment by mzur** [comment]
@nilshoerrmann Did you hear anything about a fix, yet?

**Comment by nilshoerrmann** [comment]
No, I didn‘t, sorry!

**Comment by mzur** [comment]
Ok, please reopen this issue if there is anything more to discuss.
