### ISSUE TITLE
Invalid CSRF token question

### ISSUE THREAD

**Issue by trych** [mzur/kirby-uniform#216]
Hi there!

I am setting up a rather complex form that is submitted via AJAX. Testing this on my own machine it worked fine, but I got the response from other people testing this that they could not submit the form. One sent me a screenshot that showed an error `The CSRF token was invalid.`

Now, after doing some research I am fairly certain that this is the cache issue that is [described in the docs](https://kirby-uniform.readthedocs.io/en/latest/answers/#how-can-i-have-one-or-more-forms-on-cached-pages-that-are-submitted-via-ajax).

But I am afraid I don't quite understand what I need to do with the code that I am seeing there. Specifically my question is, when exactly do I need to manually set the token via JS? On page load? Before I submit? At some other point? It's a bit hard for me to debug, since the error was never happening on my machine.

It also mentions

> you can add an uncached route to your Kirby config file

How can I make the route uncached?

Thank you!

**Comment by mzur** [comment]
I'll have a look at this when I have a little spare time. But generally it's best to ask these things in the Kirby forum since more people can help you there.

**Comment by mzur** [comment]
An AJAX form should work fine if you [exclude](https://getkirby.com/docs/guide/cache#caching-pages) the page containing the form from being cached. Do you maybe run the page on multiple domains (e.g. `www.example.com` and `example.com`)? I've experienced caching issues in cases like these and had to implement a redirect to only one of these versions (e.g. only `example.com`) for the cache to work properly. These were also cases where everything worked fine on my machine and only the clients reported issues.

**Comment by mzur** [comment]
Please reopen if there is anything else to discuss.
