### ISSUE TITLE
Choose Date Format for Form Fields

### ISSUE THREAD

**Issue by frankziski** [mzur/kirby-uniform#222]
When using Date-Fields inside the send e-mails it would be nice to set a specific date format for the output like 'd.m.Y'.

I tried to help myself by manually changing the field value inside the mail template to match my wanted date format, but i dont see any chance to do that in the subject of the mail.

**Comment by mzur** [comment]
You can update the form data using the [`data()`](https://kirby-uniform.readthedocs.io/en/latest/methods/#datakey-value-escape-true) method. Example:
```php
if (kirby()->request()->is('POST')) {
    $form->honeypotGuard(); // Run validation and guard.
    $date = new DateTimeImmutable($form->data('date'));
    $form->data('date', $date->format('d.m.Y'));
    $form->emailAction([
        'to' => 'me@example.com',
        'from' => 'info@example.com',
    ]);
}
```

**Comment by frankziski** [comment]
thanks a lot. That worked.
Is this data() method part of the documentation? If not you may include it :)

**Comment by mzur** [comment]
Yes, it's documented (I've included the link in my previous comment).
