### ISSUE TITLE
PHP Deprecated htmlspecialchars(): Passing null to paramete

### ISSUE THREAD

**Issue by veryrobert** [mzur/kirby-uniform#223]
**Ran into this error after updating my PHP version to 8.1:**
_htmlspecialchars_decode(): Passing null to parameter #1 ($string) of type string is deprecated_

`Whoops\Exception\ErrorException …/site/plugins/kirby-uniform-master/vendor/mzur/kirby-form/src/Form.php332`

`    protected function decodeField($data) {
        return is_array($data)
            ? array_map([$this, 'decodeField'], $data)
            : htmlspecialchars_decode($data);
    }
 `

Updated with a conditional and seems to have fixed the error. 

`    protected function decodeField($data) {
        return is_array($data)
            ? array_map([$this, 'decodeField'], $data)
            : htmlspecialchars_decode($data ?: '');
    }`

**Comment by mzur** [comment]
Which version of Uniform do you use? This was fixed in kirby-form [v3.0.1](https://github.com/mzur/kirby-form/releases/tag/v3.0.1) which is included in Uniform [v5.0.2](https://github.com/mzur/kirby-uniform/releases/tag/v5.0.2).

**Comment by mzur** [comment]
@adamkiss Well-spotted, thanks! I've removed the version constraint so people get the latest version. However, I think the HTML encoding was only introduced in v5.

**Comment by mzur** [comment]
Please reopen if there is anything else to discuss.
