### ISSUE TITLE
Plugin is not moved by `getkirby/composer-installer` 

### ISSUE THREAD

**Issue by raphaelokon** [mzur/kirby-uniform#230]
**Describe the bug**
When adding "mzur/kirby-uniform" to a `composer.json` and installing the plugin, it is not moved from the `vendor` directory to either `site/plugins` nor a custom path specified via "kirby-plugin-path".
Other plugins are moved fine by `getkirby/composer-installer`.

**To Reproduce**
1. `composer require mzur/kirby-uniform`
2. `composer update`

**Expected behavior**
Expected that the plugin is moved from `vendor` directory to either `site/plugins` or a custom path specified via "kirby-plugin-path".

**Comment by HENNIROCKS** [comment]
> […] Expected that the plugin is moved from `vendor` directory to either `site/plugins` or a custom path specified via "kirby-plugin-path".

@mzur I'm having the same problem, +1

**Comment by mzur** [comment]
This is now supported in v5.3.0.
