### ISSUE TITLE
Post/Redirect/Get not working

### ISSUE THREAD

**Issue by arnoson** [mzur/kirby-uniform#231]
Do I understand correctly that the Post/Redirect/Get pattern should work out of the box? At least #154 indicates that a session based Post/Redirect/Get is used. 

My controller looks like this:

```php
return function ($kirby, $page) {
  $form = new Form(...);

  if ($kirby->request()->is('POST')) {
    $form->logAction([
      'file' => kirby()->roots()->site() . '/messages.log',
    ]);
  }

  return compact('form');
};
```

and the template like this:

```php
<?php if ($form->success()): ?>
Success!
<?php else: ?>
<form>...</form>
<?php endif; ?>
```

If the form submission was successfull I see the success message and the form is not rendered anymore. But if I realod the page a new form submission is logged.

I would expect that a reload of the success page doesn't cause a re-submission.

**Comment by mzur** [comment]
You may have a point here. I think the redirect is only done on a validation error. If the form submission is successful, no redirect happens. Although Uniform >=v3 always worked like this, this should probably be fixed (if it can be done in a backwards-compatible way). I'll look into it.
