### ISSUE TITLE
Bug with Honeypots guard and the autocomplete attribute

### ISSUE THREAD

**Issue by psntr** [mzur/kirby-uniform#235]
The `autocomplete="off"` attribute seems to be ignored on latest version of Chrome. Meaning the honeypots get triggered even by human because the autocomplete still get filled by Chrome.

I'm manually replacing the value to `new-password` as recommended on [stackoverflow](https://stackoverflow.com/questions/12374442/chrome-ignores-autocomplete-off).

**Comment by mzur** [comment]
Does it only work with `type="password"`  or can you confirm that it works with `type="text"`, too?

**Comment by psntr** [comment]
Thank you for the reply. Now the form works without modifying the attribute `autocomplete`. I must have been missing something on the controller or on my route.
