### ISSUE TITLE
Allow body in email action

### ISSUE THREAD

**Issue by arnoson** [mzur/kirby-uniform#242]
It would be great if a custom email body could be passed to the email action.
My use case is this: I use a form for a registration and want to send a confirmation email to the user:

```php
$form->emailAction([
  'from' => 'register@my-site.com',
  'to' => $form->data('email'),
  'subject' => 'Registration',
  'body' => 'Dear {{name}}, we will get back to you soon!'
])
```

If you are interested in this feature I could create a PR

**Comment by mzur** [comment]
You could use an email template for this.

Controller:
```php
$form->emailAction([
  'from' => 'register@my-site.com',
  'to' => $form->data('email'),
  'subject' => 'Registration',
  'template' => 'myemail',
])
```

Template (`templates/emails/myemail.php`):
```
Dear <?= $name ?>, we will get back to you soon!
```

**Comment by arnoson** [comment]
Yes I know about the email templates, but I wan't my non-technical clients to be able to edit and translate the email message via a text field in the panel.

**Comment by mzur** [comment]
Ok, I'm convinced. Please send a PR :+1: 

If `body` is provided, it will be used for the email body. Otherwise, if `template` is provided, the template will be used. Otherwise, the action will fall back to the default email body.

**Comment by arnoson** [comment]
Great, I will submit a PR soon. Can you give me a hint on how to setup this repo for development? When I run `composer install` a not git ignored `kirby` folder is created and the tests try to require files from the `site` folder. Do you embed this plugin inside a parent kirby site?

**Comment by mzur** [comment]
Yeah, that's the Kirby installer plugin that was recently added to this repo. You can run `composer install --no-plugins`. I should probalby document this somehwere.
