### ISSUE TITLE
Distinguish between validation errors and server/action errors

### ISSUE THREAD

**Issue by arnoson** [mzur/kirby-uniform#244]
**Is your feature request related to a problem? Please describe.**
I wan't to display field validation errors right next to the corresponding field, but also display a general error message on the top of the form if something not field-related failed (e.g. an email in an action could not be send).

**Describe the solution you'd like**
It would be great, if I could easily check for any field validation errors. If there was no validation error I can assume something else went wrong and I can display a generic error message like `Due to technical reasons we couldn't save your form, please try again later or contact mail@example.com`. The reason I wan't to display a generic error is that I don't want to give too much technical details like `There was an error sending the form: "" is not a valid email address` to the user.

**Comment by mzur** [comment]
Depends on what you call "easily" :wink: Usually, you should know which actions you perform. You can check for errors of an action like this:

```php
<?php if ($form->error('Uniform\Actions\EmailAction')): ?>
    Due to technical reasons we couldn't save your form, please try again later or contact mail@example.com.
<?php endif ?>
```

Do this for all actions that are called and you should have what you want.

**Comment by arnoson** [comment]
I'm devloping a form [builder plugin](https://github.com/arnoson/kirby-forms) for kirby and therefore I'm not sure which actions the plugin user will call, but maybe checking for the actions I provide will already cover most cases. Otherwise I would propably have to do it the other way round (check all fields for errors). Just wasn't sure If there already is a built in way to do this, thanks!
