### ISSUE TITLE
Creation of dynamic property Uniform\Actions\EmailSelectAction::$data is deprecated

### ISSUE THREAD

**Issue by jamiehunterdesign** [mzur/kirby-uniform#245]
When using the` 'emailSelectAction' ` I am getting this error in debug:

`Creation of dynamic property Uniform\Actions\EmailSelectAction::$data is deprecated`

Line 25 of uniform/src/Actions/EmailSelectAction.php

`unset($this->data[self::RECIPIENT_FIELD]);`

I'm using Uniform version 5.4.0 and Kirby 3.9.3

**Comment by mzur** [comment]
Wow this was a bug all the time. Thanks for reporting!
