### ISSUE TITLE
Error on form submission after update to PHP 8.1

### ISSUE THREAD

**Issue by MikeHarrison** [mzur/kirby-uniform#247]
**Describe the bug**
I have updated my Kirby set up to:
Kirby 3.9.4
Uniform 5.4.1
PHP 8.1
When I submit a form I get the following error:

`htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated`

in `/site/plugins/kirby-form/src/Form.php384`

The dependency `kirby-form` referenced above looks like it is version 3.3.0

**To Reproduce**
1. Update to latest version of Kirby, Uniform & set to PHP 8.1
2. Submit a form

**Expected behavior**
I would expect a successful form submission

**Comment by mzur** [comment]
I just set up the Kirby Plainkit (v3.9.4) with Uniform v5.4.1 and PHP 8.1.2 and it worked with the Uniform example code from the readme. Can you please provide more details or a minimal example that reproduces the issue?

**Comment by mzur** [comment]
Please reopen if this is still relevant.
