### ISSUE TITLE
Option for a custom message in guards

### ISSUE THREAD

**Issue by MikeHarrison** [mzur/kirby-uniform#249]
**Is your feature request related to a problem? Please describe.**
When using the honeypot or honeytime guards, there is no way to customise the message displayed when they are triggered.

**Describe the solution you'd like**
Add a 'message' option to these guards, to allow a custom message to be displayed.

**Comment by mzur** [comment]
You can customize the messages by overriding the language variables. To do this, [activate the multi-lang feature](https://getkirby.com/docs/guide/languages/introduction#enabling-the-multi-lang-feature-in-the-panel) (even if you only have one language). You can then override variables in a language file (here: `site/languages/en.php`) like this:

```php
return [
  'code' => 'en',
  'default' => true,
  'direction' => 'ltr',
  'locale' => 'en_US',
  'name' => 'English',
  'url' => '/',
  'translations' => [
    'uniform-filled-potty' => 'You did bad things!',
  ],
];
```
