### ISSUE TITLE
[K4] 4.0 Compatibility

### ISSUE THREAD

**Issue by afbora** [mzur/kirby-uniform#252]
> // site\plugins\kirby-uniform-5.5.0\vendor\getkirby\cms\src\Cms\Page.php
> Type of Kirby\Cms\Page::$site must be ?Kirby\Cms\Site (as in class Kirby\Cms\ModelWithContent)

**Comment by mzur** [comment]
What did you do to test this? Recently there was an [reported issue](https://forum.getkirby.com/t/site-is-blank-with-addition-of-uniform-plugin/29705/5?u=mzur) with the bundled vendor files. I just fixed this in #253. Maybe that was what you were seeing, too?

**Comment by afbora** [comment]
![screen-capture-1699-Kirby CMS Debugger-localhost](https://github.com/mzur/kirby-uniform/assets/3393422/d828e953-1eb0-4ad1-af71-811ec54926ab)

**Comment by mzur** [comment]
Could you give me some more details, please? I:

1. Cloned the Plainkit
2. Replaced the `kirby` directory with `v4.0.0-beta.2`
3. Copied the plugin to the plugins folder
4. Set up the basic form from the Uniform readme
5. Went to the site homepage

And it worked.

Also, Kirby was erroneously included in the bundled vendor files (as I said above). The error in your screenshot really looks like you used the buggy version of Uniform.

**Comment by afbora** [comment]
@mzur I realized that kirby version in your plugin dependency is 3.9.7. I installed plugin dependencies from plugin folder not from root composer. Since kirby 4.0 stable version isn't released, plugin kirby version (`"getkirby/cms": "^3.5 || ^4.0"`) installed as 3.9.7. 

So this issue will be fixed when 4.0 stable version released, right?

**Comment by mzur** [comment]
I don't know as long as I can't reproduce the error. Uniform 5.5.1 should also work with Kirby 3.

**Comment by afbora** [comment]
I mean that my main kirby version is 4.0.0-beta.2 and kirby version is 3.9.7 in your plugin dependency. I think conflicts two different kirby versions.

**Comment by afbora** [comment]
Oh, sorry. I missed that. Error gone when I don't run plugin composer 👍
