### ISSUE TITLE
Plugin not moved to plugins folder

### ISSUE THREAD

**Issue by owzim** [mzur/kirby-uniform#254]
**Describe the bug**

Same as mentioned in #230 

**To Reproduce**

- `$ composer require mzur/kirby-uniform`
- `$ composer show -i | grep uniform` -> `mzur/kirby-uniform v5.5.1 A versatile Kirby plugin to handle web form actions.`
- `$ ls -al site/plugins | grep uniform` -> ***nothing***

The two dependencies `mzur/kirby-flash` and `mzur/kirby-form` DO get moved to the `plugins` folder, but they're not even kirby plugins

---

**Additional context**
Composer version 2.6.2
kirby 3.9.7

Other plugins install fine

**Comment by mzur** [comment]
Thanks for reporting. Could you please try it with `composer require mzur/kirby-uniform:dev-patch-1` from the linked PR?

**Comment by bezin** [comment]
I tested it, this fixes the issue 👍

**Comment by mzur** [comment]
Thanks!
