### ISSUE TITLE
Translations not working properly

### ISSUE THREAD

**Issue by gerricom** [mzur/kirby-uniform#256]
**Describe the bug**
Yesterday I got in touch with a person who wanted to submit a contact form on our webpage but she was unable to because she didn't understand the calculation field. I was kind of "hm whats up - this is cleary this plus this".... but when I visited our form I saw that in reality the field is only showing "Please calculate 5 4" without "plus" between both numbers.
After submitting the form you also don't get the correct error message, instead: `Uniform\Guards\CalcGuard rejected the request.`.

**To Reproduce**
1. Use Kirby 3.9.7 and Uniform 5.5.1 or 5.5.0
2. Have a kirby config with `locale` set to `de_DE`
3. Create a form that includes `uniform_captcha()`
4. Look at the form

**Expected behavior**
Translations should be shown correctly

**Additional context**
I first thought of an error within our kirby config. But even without a locale set the translations are not showing up.

I then did stepwise downgrades of uniform. 5.5.0 also shows this behaviour while 5.4.2 is working fine. I looked at the diff of both versions but I'm not able to find out what causes this problem... ?

**Comment by mzur** [comment]
What you describe sounds like this issue: https://github.com/Daandelange/k3-translations/issues/12 Do you have k3-translations installed?

You can also use the (new) [Honeytime guard](https://kirby-uniform.readthedocs.io/en/latest/guards/honeytime/). It works very well and the user doesn't have to enter anything any more.

**Comment by gerricom** [comment]
Hmmm - no I'm not using k3-translations. I'll check if any other package is the reason for my problems. But in the meantime I have switched of the calc guard and give honeytime a shot. Thanks for that tip!

**Comment by mzur** [comment]
Which other extensions do you have installed?

**Comment by gerricom** [comment]
Those are the requirements in my composer.json

```
		"php": ">=7.1.0",
		"getkirby/cms": "^3.0",
		"distantnative/retour-for-kirby": "^4.0",
		"oblik/kirby-link-field": "^5.0",
		"mzur/kirby-uniform": "5.4.2",
		"lukasbestle/kirby-versions": "^1.0"
```

I turned them off individually but this had no effect. I guess, I'll have to start a demo project and see if I can reproduce the behaviour there...

**Comment by mzur** [comment]
@gerricom Any news on this? Have you tried to start from scratch?
