### ISSUE TITLE
Echo values in specific order in the email snippet

### ISSUE THREAD

**Issue by loasca** [mzur/kirby-uniform#26]
Thank you for this great plugin, it works wonder.

I was trying to output the from values in a specific order in teh email snippet but I'm having an hard time with that.
I tried using `echo $form->value('name')` with no success.

Am I missing something or there ins't any way to avoid the `foreach`?

**Comment by mzur** [comment]
Hi, thanks :-)

In the snippet the `$form` variable is not the Uniform object but a simple associative array of the form data. So you can echo the value of `name` with `echo $form['name']`.

**Comment by loasca** [comment]
Thanks a lot. I knew that I was missing something!

**Comment by mzur** [comment]
You're welcome ;-)
