### ISSUE TITLE
Webhook

### ISSUE THREAD

**Issue by mzur** [mzur/kirby-uniform#29]
As suggested [here](http://blog.the-inspired-ones.de/kirby-with-uniform#comment-1876184458), add an action that can trigger arbitrary webhooks.

Use the [remote](http://getkirby.com/docs/toolkit/api#remote) object from the Toolkit.

**Comment by wtip** [comment]
Do you have some rough sample code for something like this?
If I wanted to go about implementing this myself would I just put it in site/plugins/uniform-actions.php ?

**Comment by mzur** [comment]
>  If I wanted to go about implementing this myself would I just put it in site/plugins/uniform-actions.php ?

Yes, that's right. Just have a look at the [email](https://github.com/mzur/kirby-uniform/blob/5cb0955213dd9000465b0370febcf07212100ab8/uniform/lib/UniForm.php#L373-449) or the [email-select](https://github.com/mzur/kirby-uniform/issues/30#issuecomment-78237605) actions for how to implement one.

An action is basically a callback function that expects the form data (not the Uniform object) as associative array and the action array as arguments. With this, you can do anything you want. The action callback finally should return an array with a `success` boolean and a `message` string.

For the webhook action you could specify the URL and the HTTP method to use in the action array. In the action callback, you then take the form data (maybe convert it to JSON) and send it to the URL with the specified method. That should suffice for basic webhook usage.
