### ISSUE TITLE
Is it possible to send the form to a particular email depending on user choice?

### ISSUE THREAD

**Issue by mattanddesign** [mzur/kirby-uniform#30]
I want to create a form where you can select one of three options then, depending on your choice, it sends to a particular address. e.g. say i select 'General enquiry' it would send to to *general@email.com* though if i choose 'Marketing' it sends to *marketing@email.com*.

 Is this possible?

**Comment by mzur** [comment]
Sure, but you have to implement a new action as "preprocessor" for the existing email action:

```php
uniform::$actions['email-select'] = function($form, $actionOptions) {
	$recipient = $form['_recipient'];

	if (!in_array($recipient, $actionOptions['allowed-recipients'])) {
		return array(
			'success' => false,
			'message' => l::get('uniform-email-error').' Invalid recipient.'
		);
	}

	unset($form['_recipient']);
	unset($actionOptions['allowed-recipients']);
	$actionOptions['to'] = $recipient;

	return call_user_func(uniform::$actions['email'], $form, $actionOptions);
};
```

Just put the above code in a `site/plugins/uniform-actions.php` file.

The action is then used just like the `email` action but without the `to` option. Note the new required option `allowed-recipients`, too. Without checking the recipients on the server, the user would be able to send emails to arbitrary recipients.

```php
$form = uniform(
	'contact-form',
	array(
		'required' => array(
			'_from'      => 'email'
		),
		'actions' => array(
			array(
				'_action' => 'email-select',
				'sender'  => 'info@my-domain.tld',
				'subject' => $site->title()->html() . ' - message from the contact form',
				'allowed-recipients' => array(
					'general@email.com',
					'marketing@email.com'
				)
			)
		)
	)
);
```

Finally, add the `_recipient` select field to your form:

```php
<select name="_recipient" id="_recipient">
  <?php $value = $form->value('_recipient') ?>
  <option value="general@email.com"<?php e($value=='general@email.com', ' selected')?>>General enquiry</option>
  <option value="marketing@email.com"<?php e($value=='marketing@email.com', ' selected')?>>Marketing</option>
</select>
```
I've not tested all this, so tell me if you encounter any errors.

That's a pretty good idea by the way. I'll add it to the other proposed actions.

**Comment by mattanddesign** [comment]
Thanks! I'll let you know how I get on with it.

**Comment by mattanddesign** [comment]
Worked like a charm, thanks! 

I did make one adjustment though:

```javascript
'allowed-recipients' => array(
	'general@email.com' => 'general',
	'marketing@email.com' => 'marketing'
)
```
 Meant I could get away without having the emails as plain text on the page.

You can see it live at https://skedgo.com/contact

**Comment by mzur** [comment]
Great work! Glad to see it in action :-)
