### ISSUE TITLE
Sending to multiple recipients doesn't work

### ISSUE THREAD

**Issue by lekkerduidelijk** [mzur/kirby-uniform#34]
Thanks for your great plugin @mzur!

I have an issue with multiple recipients. The email needs to be delivered to multiple accounts. So I setup two actions in the array like described in the readme file.

The second action in the array is not executed, only the first email is sent...

```php
return function($site, $pages, $page) {

  $recipient  = "email1@lekkerduidelijk.nl";
  $recipient2 = "email2@lekkerduidelijk.nl";
  $sender     = "sender@website.com";
  $subject    = "[website.com] Contact";

  $form = uniform(
    'contact-form',
    array(
      'required' => array(
        'naam'   => '',
        '_from'  => 'email',
        'bericht'   => '',
      ),
      'actions' => array(
        array(
          '_action' => 'email',
          'to'      => $recipient,
          'sender'  => $sender,
          'subject' => $subject,
          'snippet' => 'uniform-email-txt'
        ),
        array(
          '_action' => 'email',
          'to'      => $recipient2,
          'sender'  => $sender,
          'subject' => $subject,
          'snippet' => 'uniform-email-txt'
        ),
      )
    )
  );
  return compact("form");
};
```

I tried to add multiple values to the 'to' key in the array but that didn't work :)

Hope you can help me out.

**Comment by lekkerduidelijk** [comment]
Sorry about this. I just received the e-mails. :confused: 
It was a mail queue issue, coincidently happening on different mail servers at the same time. What are the odds...

**Comment by mzur** [comment]
Never mind; I'm always happy about feedback although I currently don't have a lot of spare time for tending this plugin.
