### ISSUE TITLE
It's a little... sexual. Maybe?

### ISSUE THREAD

**Issue by labo-css** [mzur/kirby-uniform#41]
I laughted a lot while reading this part : https://github.com/mzur/kirby-uniform#honeypot

"name="fill-me" id="fill-me" class="uniform__potty"
Made me think about this : https://www.youtube.com/watch?v=54OYS_mZlBE

**Comment by chbach** [comment]
Oh, yeah that’s the way...

**Comment by labo-css** [comment]
FILL ME CHANDLER
