### ISSUE TITLE
Email confirmation displayed multiple times

### ISSUE THREAD

**Issue by malvese** [mzur/kirby-uniform#47]
I have configured a form with multiple recipients, the confirmation message is displayed as many times as there are recipients.

```
'actions'  => array(
            array(
              '_action' => 'email',
              'to'      => 'postmaster@xxx.com',
              'sender'  => 'postmaster@xxx.com',
              'subject' => 'Amitievillages.org - Questionnaire projet',
              'snippet' => 'mail-form'
            ),
            array(
              '_action' => 'email',
              'to'      => 'yyy@xxx.com',
              'sender'  => 'yyy@xxx.com',
              'subject' => 'Amitievillages.org - Questionnaire projet',
              'snippet' => 'mail-form'
            ),
            array(
              '_action' => 'email',
              'to'      => 'contact@xxx.org',
              'sender'  => 'yyy@xxx.com',
              'subject' => 'Amitievillages.org - Questionnaire projet',
              'snippet' => 'mail-form'
            )
         )
```

Here's the result:
![multiple_submit](https://cloud.githubusercontent.com/assets/193492/7708249/b5755848-fe54-11e4-9205-5742c64c2498.png)

It seems to be because of the ".=" instead of "=" at line 431 in UniForm.php, but I'm not sure if it can break in some case I haven't tested.

**Comment by mzur** [comment]
If you use `$form->message()` the [feedback messages of *all* actions are displayed](https://github.com/mzur/kirby-uniform#messageaction--false). To display the message of only one action (e.g. the first) use `$form->message(0)`.

**Comment by malvese** [comment]
Doh, it had totally escaped me, sorry!
So is it either one message or all of them? Oh well if I ever need only some of them I guess I can use ```$form->message()``` several times with a different action as a parameter.

**Comment by mzur** [comment]
> So is it either one message or all of them? Oh well if I ever need only some of them I guess I can use `$form->message()` several times with a different action as a parameter.

Yes, you can do that. In a future version something like `$form->message([0, 2, 3])` could be implemented, too. You can open an issue or make a pull request for this if you like ;-)

**Comment by malvese** [comment]
Oh man, I'm not even a half developer. I know just enough to be dangerous. But I'll take a gander ;)

**Comment by mzur** [comment]
Then I'm happy to help ;-) But I won't have time for new Uniform features any time soon.
