### ISSUE TITLE
Multiple forms on one page

### ISSUE THREAD

**Issue by mingyeungs** [mzur/kirby-uniform#48]
The echoValue('field-name') method is not bound to the form instance.
Is this a bug or the intended behavior? Here's an example:

```
<?php
    $formA = uniform('formA', array(...));
    $formB = uniform('formB', array(...));
    $formC = uniform('formC', array(...));
?>

<form id="formA" action="<?= $page->url(); ?>#formA" method="post">
    <label for="name">Name</label>
    <input type="text" name="name" value="<?php $formA->echoValue('name'); ?>">
    <button type="submit" name="_submit" value="<?= $formA->token(); ?>">Submit</button>
</form>

<form id="formB" action="<?= $page->url(); ?>#formB" method="post">
    <label for="name">Name</label>
    <input type="text" name="name" value="<?php $formB->echoValue('name'); ?>">
    <button type="submit" name="_submit" value="<?= $formB->token(); ?>">Submit</button>
</form>

<form id="formC" action="<?= $page->url(); ?>#formC" method="post">
    <label for="name">Name</label>
    <input type="text" name="name" value="<?php $formC->echoValue('name'); ?>">
    <button type="submit" name="_submit" value="<?= $formC->token(); ?>">Submit</button>
</form>
```

Let say I enter 'David' in the name field of **form A** and click submit, what I expect is:
1) form A get submitted;
2) form A get cleared;
2) other forms remain intact;

While the actual result is:
1) form A get submitted;
2) form A get cleared;
2) The name field in **form B** & **form C** both become 'David';

It's arguable that the same name shouldn't appear twice, but since I'm calling an instance method echoValue(), I suppose the correct behavior should be the expected one instead of the actual one now?

**Comment by mzur** [comment]
You're right. As it is, the forms get the form data with the `get()` function (so if the form fields have the same name, all forms will get the same data), but the data isn't cleared if the form wasn't targeted by the request. I'll push a fix for this.

**Comment by mzur** [comment]
@mingyeungs is everything ok now? Although I closed this issue, I'd love to hear your feedback.

**Comment by mingyeungs** [comment]
@mzur Yes it's working as expected now, thanks for the quick fix.
