### ISSUE TITLE
Uppercase causing php error

### ISSUE THREAD

**Issue by hotovec** [mzur/kirby-uniform#50]
On server whit uppercase sensitivity, uniform.php require_once is causing error.
Unify letter case to fix issue.

```
require_once(__DIR__ . DS . 'lib' . DS . 'UniForm.php'); // uppercased filename to fix err
```

**Comment by mzur** [comment]
Are you referring to [this](https://github.com/mzur/kirby-uniform/blob/9e277945f6bc31c1a7699cfc5be48b07071010d8/uniform/uniform.php#L7) line? I'm afraid I don't see what you mean since the file *is* called `UniForm.php`.

**Comment by hotovec** [comment]
yes

**Comment by mzur** [comment]
So, what's the problem again? The file is named `UniForm.php` and it is loaded as `UniForm.php`, too. I don't see any discrepancies with the letter case.
