### ISSUE TITLE
Sending multiple checkbox options

### ISSUE THREAD

**Issue by buschfeuer** [mzur/kirby-uniform#51]
Is there a way to send multiple checkbox options?

Output should be like this:

"Your selected items:
Item 1
Item 3
Item 6
..."

**Comment by mzur** [comment]
That's currently not possible but it's a very good point. I'll add this feature to the roadmap but I can't make any promises as to when I will be able to tackle it.

Brainstorming:

- Use the array syntax to send multiple values with the form like this ([ref](http://stackoverflow.com/a/1978788/1796523)):
```html
<label for="item-1">
   <input type="checkbox" name="items[]" id="item-1" value="item 1"/> Item 1
</label>
<label for="item-2">
   <input type="checkbox" name="items[]" id="item-2" value="item 2"/> Item 2
</label>
```

- Add validation for fields with an array of values. Maybe limit validation to required/not required?

- Figure out how `$form->value('items')` can work with the array of values to refill the form in case of an error

- Extend all form actions to be able to handle arrays of values

**Comment by dennisfrank** [comment]
Hi @mzur! Any updates on this?

**Comment by mzur** [comment]
No, sorry. I'm currently writing my master's thesis and I don't even have the nerve to properly review the two pull requests :confused: I'd love to see more contributors for v2.2 since this plugin seems to be quite popular.

**Comment by mzur** [comment]
Uniform v2.2 should be able to handle this sort of thing now. You can implement an array form field like this:

```html
<input type="text"<?php e($form->hasError('qty'), ' class="erroneous"')?>  name="qty[]" value="<?php echo $form->value('qty')[0] ?>" />
<input type="text"<?php e($form->hasError('qty'), ' class="erroneous"')?>  name="qty[]" value="<?php echo $form->value('qty')[1] ?>" />
<input type="text"<?php e($form->hasError('qty'), ' class="erroneous"')?>  name="qty[]" value="<?php echo $form->value('qty')[2] ?>" />
```

Note that the `echoValue()` helper doesn't work with these kind of fields so you have to use `echo $form->value()`. If you add the field to the `required` array, Uniform will check if at least one array item is not empty. For validation you will have to implement your own functions and add them to the `v::$validators` array of the Toolkit.

Please report any bugs you encounter. Thanks!

**Comment by dennisfrank** [comment]
Thanks @mzur. Christmas came early! :christmas_tree: 

I will try it out in January and let you know of any issues.
