### ISSUE TITLE
How to make this form to work via AJAX?

### ISSUE THREAD

**Issue by seleckis** [mzur/kirby-uniform#55]
This form works only using old-school refreshable method. It needs to be ajaxable :)

**Comment by mzur** [comment]
I just wrote a [blog post](http://blog.the-inspired-ones.de/ajax-uniform) about this. I hope this will answer your question ;-)

**Comment by seleckis** [comment]
Awesome! Thank you! But I have already made my own solution. Of course it is similar to yours.
