### ISSUE TITLE
Form won't display after installation

### ISSUE THREAD

**Issue by iamachimp** [mzur/kirby-uniform#56]
Just followed the instructions on basic form installation, but unfortunately I'm getting the following error:

```
Name Notice: Undefined variable: form in D:\projects\kirby\site\templates\contact.php on line 8

Fatal error: Call to a member function hasError() on null in D:\projects\kirby\site\templates\contact.php on line 8
```

Any ideas on what's happening here?

**Comment by mzur** [comment]
Looks like your controller doesn't work as it should. Take a look at the [blog post](http://blog.the-inspired-ones.de/kirby-with-uniform) on how to set up the controller properly.

**Comment by iamachimp** [comment]
@mzur 

Hmm, that's odd. I just fired up php again and it displays fine without making any changes. Not sure what was happening before. I suppose there's nothing wrong and this issue can be closed. Thanks.
