### ISSUE TITLE
executing multiple actions

### ISSUE THREAD

**Issue by bvdputte** [mzur/kirby-uniform#57]
Is it possible to execute multiple actions upon form submit?

e.g. "email" + "log"
-> email the form to an e-mail address, but also save the submissions to a logfile

or e.g. "email-select" + "log"
-> same as above, but email to a chosen predefined address

I hope I'm clear?
Thanks

**Comment by mzur** [comment]
Sure, you can add as many actions as you like. Have a look at this:

```php
$form = uniform(
    'contact-form',
    array(
        'required' => array(
            'name'  => '',
            '_from' => 'email'
        ),
        'actions' => array(
            array(
                '_action' => 'email',
                'to'      => 'me@example.com',
                'sender'  => 'info@my-domain.tld'
            ),
            array(
                '_action' => 'log',
                'file'    => './reservation-form.log'
           )
       )
    )
);
```

**Comment by bvdputte** [comment]
Excellent. thanks for the _very fast_ reply.

Keep up the good work Martin!
