### ISSUE TITLE
HTML email headers and receive copy option

### ISSUE THREAD

**Issue by rzschoch** [mzur/kirby-uniform#58]
For starters, thanks a lot for your plugin!

I think, I found some issues though:

1. By using your html-email-table snippet, Mail on OS X only displays the email as plain text. Is it because of the missing html-email action that would send the correct headers to a mail client?

2. I was not able to use your receive-copy option. For me, only the copy was sent but not the filled out form to the recipient.

Thanks again
René

**Comment by mzur** [comment]
1. You're right. You need an email service like [this one](https://github.com/mzur/kirby-uniform/issues/7#issuecomment-68592134) and then [choose it](https://github.com/mzur/kirby-uniform/wiki/Action:-Email#service) for the email action.

2. Does it work without the `_receive_copy` form field? Maybe there is something wrong with the email address provided in the [`to`](https://github.com/mzur/kirby-uniform/wiki/Action:-Email#to-required) attribute of the email service?

I noticed that the copies are sent no matter if the original email has been sent successfully or not. I think it would be better to send the the copy only if there were no issues sending the original email. I'll fix that.

**Comment by rzschoch** [comment]
That was quick, thanks.

1. Alright, decided to go with a plain text mail, for now.

2. Yes, it fully works without the `_receive_copy` form field. With the field the mail is only sent to the `_from` value not the `_to` one. I should say, that I use this feature in conjunction with `allowed-recipients`. Maybe that’s the reason?

Thanks for your fix regarding the sending copies only when the original mail was sent successfully.

**Comment by mzur** [comment]
Can you please post your controller code?

**Comment by rzschoch** [comment]
Sure, here is the controller code:

`````php
return function($site, $pages, $page) {
  // add default recipient to allowed recipients
  $recipients['default'] = c::get('project.defaultMailAddress');

  // collect allowed recipients from member pages
  foreach(page('team')->children()->visible() as $recipient) {
    $recipients[(string) $recipient->uid()] = (string) $recipient->email();
  }

  // initialize uniform with settings
  $form = uniform(
    'registration-form',
    array(
      'required' => array(
        '_from' => 'email',
        'region' => '',
        'invitation-reason' => '',
        'name-school' => '',
        'college' => '',
        'name' => '',
        'name-teacher' => '',
        'role' => '',
        'phone-business' => '',
        'class-level' => '',
        'student-quantity' => 'num',
        'preferred-date' => '',
        'last-date' => '',
        'principal' => ''
      ),
      'actions' => array(
        array(
         '_action' => 'log',
         'file' => './registration-form.log'
        ),
        array(
          '_action' => 'email-select',
          'sender' => c::get('project.senderMailAddress'),
          'subject' => (string) page('registration')->title() . ': {preferred-date} ',
          'snippet' => 'uniform-email-default',
          'allowed-recipients' => $recipients
        )
      )
    )
  );

  return compact('form');
````

**Comment by mzur** [comment]
Okay and even with the new `v2.1.6` you are only receiving the copy and not the original email?

That's a nice looking form, by the way ;-)

**Comment by rzschoch** [comment]
Thanks, and yes I updated to the new version just a few minutes after your fix.

Have a nice weekend.

**Comment by mzur** [comment]
That's weird. When you use `v2.1.6` and receive the email copy then `$email->send()` of the original email returned `true` and the mail should be sent, too. Could you post a `var_dump` of `$params` [here](https://github.com/mzur/kirby-uniform/blob/e9665b518d0e7d87bfd3fba716e6426ddf13850c/uniform/lib/UniForm.php#L561) and [here](https://github.com/mzur/kirby-uniform/blob/e9665b518d0e7d87bfd3fba716e6426ddf13850c/uniform/lib/UniForm.php#L569)?

**Comment by rzschoch** [comment]
Here are the var dumps. Thanks for your time to look on it...

````php
array(7) {
  ["service"]=>
  string(4) "mail"
  ["options"]=>
  array(0) {
  }
  ["to"]=>
  string(16) "r.zschoch@me.com"
  ["from"]=>
  string(19) "mobiklasse@ofaj.org"
  ["replyTo"]=>
  string(27) "rene.zschoch@googlemail.com"
  ["subject"]=>
  string(30) "Inscription mobiklasse.de: sdf"
  ["body"]=>
  string(989) "### Dans quelle région se trouve votre école?:
Aquitaine

### J’aimerais inviter la mobiklasse.de:
En cours

### Nom et type d’établissement:
sdf

### Académie:
sdf

### Prénom et nom:
sdf

### Fonction:
sdf

### Tél. privé, si possible:
435

### Tél. professionnel:
234

### Nom du professeur d’allemand:
dsf

### Pour quelles classes souhaitez-vous inviter le DeutschMobil?:
sdf

### Nombre de classes et d’élèves par groupe (25 max.):
23

### Pendant quel mois préférez-vous une visite? (et quel jour?):
sdf

### Y a-t-il un/e assistant/e de langue au sein de l’école?:
Non

### Dernière visite de mobiklasse.de (auparavant DeutschMobil) (Date ou Jamais):
sdf

### Jusqu’à quelle date les élèves concernés doivent-ils décider, s’ils vont choisir l’alleman?:
gfd

### Nombre d’années d’étude de la langue allemande:
sdf

### 1ère ou 2ème langue étrangère:
sdf

### Remarques:
sdf

### Le responsable d’établissement, Monsieur/Madame:
sdf

"
}
array(7) {
  ["service"]=>
  string(4) "mail"
  ["options"]=>
  array(0) {
  }
  ["to"]=>
  string(27) "rene.zschoch@googlemail.com"
  ["from"]=>
  string(19) "mobiklasse@ofaj.org"
  ["replyTo"]=>
  string(27) "rene.zschoch@googlemail.com"
  ["subject"]=>
  string(39) "Copie : Inscription mobiklasse.de: sdf"
  ["body"]=>
  string(989) "### Dans quelle région se trouve votre école?:
Aquitaine

### J’aimerais inviter la mobiklasse.de:
En cours

### Nom et type d’établissement:
sdf

### Académie:
sdf

### Prénom et nom:
sdf

### Fonction:
sdf

### Tél. privé, si possible:
435

### Tél. professionnel:
234

### Nom du professeur d’allemand:
dsf

### Pour quelles classes souhaitez-vous inviter le DeutschMobil?:
sdf

### Nombre de classes et d’élèves par groupe (25 max.):
23

### Pendant quel mois préférez-vous une visite? (et quel jour?):
sdf

### Y a-t-il un/e assistant/e de langue au sein de l’école?:
Non

### Dernière visite de mobiklasse.de (auparavant DeutschMobil) (Date ou Jamais):
sdf

### Jusqu’à quelle date les élèves concernés doivent-ils décider, s’ils vont choisir l’alleman?:
gfd

### Nombre d’années d’étude de la langue allemande:
sdf

### 1ère ou 2ème langue étrangère:
sdf

### Remarques:
sdf

### Le responsable d’établissement, Monsieur/Madame:
sdf

"
}

**Comment by mzur** [comment]
Hm, maybe there is something wrong with the webserver and sending mails in rapid succession. Do you receive the original email when you request the copy but comment out [this](https://github.com/mzur/kirby-uniform/blob/e9665b518d0e7d87bfd3fba716e6426ddf13850c/uniform/lib/UniForm.php#L569) line?

**Comment by chbach** [comment]
There are actually some web hosting companies that prevent sending more than one email per request. You should check that too.

**Comment by rzschoch** [comment]
Yes, that‘s probably the reason. By commenting out the receive_copy send action the form is submitted successfully. I just contacted my hoster about the issue (https://uberspace.de/).

**Comment by rzschoch** [comment]
Hm, according to Uberspace it should be possible: https://twitter.com/renezschoch/status/640908778993549312

**Comment by mzur** [comment]
What happens if you run this code in the page controller (replace the email addresses)? Do you get the two emails?
```php
$params = array(
   'service' => 'mail',
   'to'      => 'you@example.com',
   'from'    => 'info@example.com',
   'replyTo' => 'info@example.com',
   'subject' => 'test',
   'body'    => 'test'
);
$email = email($params);

if($email->send())
{
   $params['to'] = 'you@gmail.com';
   email($params)->send();
}
```

**Comment by rzschoch** [comment]
No, I only get one email sent to the address that is defined here:

````php
$params = array(
   'service' => 'mail',
   'to'      => 'you@example.com',
   'from'    => 'info@example.com',
   'replyTo' => 'info@example.com',
   'subject' => 'test',
   'body'    => 'test'
);
````

**Comment by chbach** [comment]
Then it has obviously nothing to do with the uniform plugin, but rather with the email function. Can you check whether the first `send()` call returns true?

**Comment by rzschoch** [comment]
That’s interesting, both `send()`calls return `true` but only the first one sends an email...

**Comment by mzur** [comment]
The same code works on our Uberspace. Do you have a special PHP version or something? Else there may be something wrong with your Kirby installation. You could try it with a fresh installation.

**Comment by rzschoch** [comment]
I just tried it on another server (not Uberspace) which had the same issues. I should try it sometime using a plain default kirby installation. I close this one since it seems to be an issue on my side.

Thank’s a lot for your patient help.
