### ISSUE TITLE
Create Kirby content entry from form submission?

### ISSUE THREAD

**Issue by tobystokes** [mzur/kirby-uniform#59]
Is it possible to create a new Kirby content page from a form submission?
The use-case: if entries become content, then we can also generate reports of all entries, CMS admins can process/edit/delete entries after submission.

Looking at the log action, it's not far off a YAML file, so if it was saved to e.g. /content/form/{entryID}/form.txt then we're already not far off.

This is a feature request not a bug, but before I give it a try, I wondered whether it had been attempted before?

**Comment by chbach** [comment]
This shouldn’t be a problem. Just create a new action and use the `create` method for a new page. <http://getkirby.com/docs/cheatsheet/pages/create>

**Comment by tobystokes** [comment]
Ah yes, as so often happens with Kirby, it really is that simple!
It works for me, if I get around to making a proper generic version, I might send a PR.
Thanks

**Comment by mzur** [comment]
:+1: for a PR

**Comment by chrishaff** [comment]
:+1: for a PR

**Comment by tobystokes** [comment]
Well I decided the version I did quickly wasn't really robust or generic enough to be included in @mzur 's proper version, but you're welcome to use what I did as a starting point - it basically works great, but you may want to add a bit of extra configuration for your needs.

In this branch
https://github.com/tobystokes/kirby-uniform/tree/pages
is a new action called 'pages', and here's an example controller:
https://github.com/tobystokes/kirby-uniform/wiki/Action:-pages
