### ISSUE TITLE
Uniform for building a registration form?

### ISSUE THREAD

**Issue by rzschoch** [mzur/kirby-uniform#60]
It surely is possible to use uniform for building a registration form that adds new kirby users with a specific role, is it? What would be the best way to do it?

Any tip would be very appreciated.

**Comment by chbach** [comment]
Same procedure as described in #59 :

Create a new action and use some Code like described here: 
<http://getkirby.com/docs/cheatsheet/users/create>

**Comment by rzschoch** [comment]
Thanks, read it some days ago and forgot about it...
