### ISSUE TITLE
How to send form via Postmark?

### ISSUE THREAD

**Issue by iamachimp** [mzur/kirby-uniform#61]
As the title says, I'm trying to setup kirby-uniform to send out my forms via Postmark, or some 
other transactional email service. 

Does anyone know how to set this up or has a ready baked solution?

Thanks

**Comment by chbach** [comment]
It looks like Kirby has Postmark support built-in, so you don’t have to change anything for Uniform. You only have to make the settings in the Kirby configuration so that your emails get sent via Postmark and not via the php mail() function. 

Have a look at <http://getkirby.com/blog/email-plugin>

**Comment by mzur** [comment]
You can use Postmark by using the `postmark` [email service](https://github.com/getkirby/toolkit/blob/4a686fbb58f6568957a9d9159ebaf2fb24bb60aa/lib/email.php#L236-L270). To use it with the Uniform email action you only have to specify the [service](https://github.com/mzur/kirby-uniform/wiki/Action:-Email#service) and [service-options](https://github.com/mzur/kirby-uniform/wiki/Action:-Email#service-options) like this:
```php
'actions' => array(
   array(
      '_action' => 'email',
      'to'      => (string) $page->email(),
      'sender'  => 'info@my-domain.tld',
      'subject' => $site->title()->html() . ' - message from the contact form',
      'service' => 'postmark',
      'service-options' => array(
         'key' => 'yourkey'
      )
   )
)
```

**Comment by iamachimp** [comment]
@mzur 

Thank you, it's working perfectly. I'm still not sure where I set the

```'to'      => (string) $page->email()``` , so I manually 
set it to:

```'to'      => 'info@dryinkdesign.com'``` for now.

**Comment by chbach** [comment]
This means that the txt file of your page is expected to have a field named 'email' in it. So basically you would have something like: 

```md
Title: Contact Form

----

email: mail@example.com

----
```

**Comment by iamachimp** [comment]
@chbach 

Oh, that makes sense. Thank you so much -- it's working correctly now. 
I guess the issue can be closed.
