### ISSUE TITLE
Form fields validation options?

### ISSUE THREAD

**Issue by iamachimp** [mzur/kirby-uniform#62]
I was wondering if uniform has any fields validation options build in aside from ```'email'```?

I would like to limit the character count on some fields, and set minimum on others. Is this currently possible? I found that I can use ```'num'``` for integer values, but that's not what I need at the moment. 

If not, what would be the best way to extend it?

Thank you.

**Comment by chbach** [comment]
Have a look at <http://getkirby.com/docs/cheatsheet/#validators>

**Comment by mzur** [comment]
By default only the standard validators are available (see the link above). But you can easily extend them by extending the [`v::$validators` array](https://github.com/getkirby/toolkit/blob/09e6e082ca5381df3f8dcf5cce220ca80fdb755e/lib/v.php#L51) with a custom function. Only validator functions with a single argument (the form field value) are supported, though.

**Comment by iamachimp** [comment]
Thank you. I've looked at the validators docs, but I'm still not sure how to implement this. I have this in my contact controller:

```
<?php

return function($site, $pages, $page) {

   $form = uniform('contact-form', array(
         'required' => array(
            '_from' => 'email',
            'name' => '',
            'message' => '',
            'ip' => '',
            'host' => ''
            ),
         'actions' => array(
   array(
      '_action' => 'email',
      'to'      => (string) $page->email(),
      // 'message' => (string) $page->message(),
      'sender'  => 'contact@domain.com',
      'subject' => $site->title()->html() . ' - Contact Form',
      'service' => 'postmark',
      'service-options' => array(
      'key'    => 'my-key-123'
      )
   )
)
      )
   );

   return compact('form');
};
```

Now, how would I, for example, set a maximum character limit of 500 on the ```'message'``` field?

**Comment by mzur** [comment]
Like this:

```php
<?php

return function($site, $pages, $page) {
	v::$validators['notTooLong'] =  function($value) {
		return strlen($value) <= 500;
	};

	$form = uniform('contact-form', array(
		'required' => array(
			'_from' => 'email',
			'name' => '',
			'message' => 'notTooLong',
			'ip' => '',
			'host' => ''
		),
		// ...
```

**Comment by iamachimp** [comment]
Thank you, so I just define the validators I need before instantiating the form. Perfect!

I guess that settles it, and I'm sorry about being a pain in the butt.

**Comment by mzur** [comment]
> I'm sorry about being a pain in the butt

Never mind; every question you ask doesn't need to be asked by someone else in the future ;-)
