### ISSUE TITLE
Fields that don't validate should show an error even if not all required fields are filled

### ISSUE THREAD

**Issue by minimalweb** [mzur/kirby-uniform#63]
If I have a form with e.g. 3 required field and one of them should also validate as an email address…

```
array(
        'required' => array(
            'name'  => '',
            'text'  => '',
            'email' => 'email'
        ),
```

…and i fill the name field with a string and the email field with a string that does not validate as an email address, only the text field is listed as erroneus, but the email field is not. The script checks first, if all required fields are there and returns false if this is not the case, before the validation of the fields even starts. That leads to confusing output for the user.

**Comment by mzur** [comment]
But that would require a more detailed way of dealing with errors, e.g. to show which fields are invalid and which missing. Otherwise the user has to pry the erroneous empty form fiels apart from those with content since the error message would only complain about "missing  _and_ invalid fields".

**Comment by MacGyer** [comment]
You could redefine the validation rules a property based algorithm. This way you can specifically define which field shall validate against which rule.

```
$form = uniform('contact-form', [
        '_from' => [
            'rules' => ['rule1', 'rule2', ...],
            'message' => // reference language file here
            'skipOnEmpty' => true/false,
        ],
        'name' => [
            'rules' => ...
        ],
        // further stuff
    ]
);
```

rules-Array can be single-dimensioned, or have the rule name as key and the value as (user defined) callable.

**Comment by mzur** [comment]
Continued in #87
