### ISSUE TITLE
How to modify the return url?

### ISSUE THREAD

**Issue by kannix** [mzur/kirby-uniform#66]
I want to append  `#contactform` to the url to scroll directly to the success/error message of the form.

**Comment by mzur** [comment]
Just add the anchor to the action URL like so (taken from the [example](https://github.com/mzur/kirby-uniform#basic)):

```html+php
<form action="<?php echo $page->url()?>#contactform" method="post">
   <!-- ... -->
</form>
```

**Comment by kannix** [comment]
Thx :+1:
