### ISSUE TITLE
Sender E-Mail in Compact Form

### ISSUE THREAD

**Issue by robertda** [mzur/kirby-uniform#70]
Hello, thank you for Kirby Uniform!
My little issue: I want to have sender email, along with name and message, in returned compacted form. Right now, i'm using as controller following code (my template has a carbon copy option):

<pre><code>
<?php
return function($site, $pages, $page) {
	$form = uniform(
    'contact-form',
    array(
        'required' => array(
            'name'  => '',
            '_from' => 'email'
        ),
         'actions'  => array(
            array(
               '_action' => 'email',
               'to'      => 'my-receive-email-adress',
               'sender'  => 'my-server-configured-email-adress',
               'subject'  => 'Message' 
				),
				array(
                '_action' => 'email',
                'to'      => 'me-too@example.com',
                'sender'  => 'my-server-configured-email-adress',
                'subject' => 'Message'              
            )
         )
      )
   );
   return compact('form');
};
?>
</pre></code>
So, i want to have returned in all received messages **me-too@example.com** adresses.
Cheers!

**Comment by mzur** [comment]
I'm not sure if I understood that correctly; so you want to add one fixed email address (me-too@example.com) to all of the sent emails?

One option is to use a `hidden` form field and submit the address with the other form data. If you don't want to disclose the address to everyone, you could extend the [default email snippet](https://github.com/mzur/kirby-uniform/blob/4b8499c1fbe114338c1cb4cd7161f6f229e70fef/snippets/uniform-email-default.php) to include the address.

**Comment by robertda** [comment]
No, is much simpler: classic contact form, with carbon copy. I want to see on returned form SENDER EMAIL ADRESS (real person who contact me) along with NAME and MESSAGE. Contact form is returning right now SENDER NAME & MESSAGE and for sender email is returning my server email adress.

Something like:
NAME: Barrack Obama
**EMAIL: president@whitehouse.gov**
MESSAGE: Obamacare is good.

**Comment by mzur** [comment]
Okay, then you have to add something like this to the default email snippet:
```php
echo "EMAIL: {$form['_from']}";
```
Don't forget to [use](https://github.com/mzur/kirby-uniform/wiki/Action:-Email#snippet) the snippet, too, instead of the simple key value listing that is done without using any snippet.

**Comment by robertda** [comment]
It worked! Thanks.
