### ISSUE TITLE
case-sensitive class name

### ISSUE THREAD

**Issue by MacGyer** [mzur/kirby-uniform#71]
Heya,

just installed uniform for Kirby2. Nice work man!

Found an issue with the plugin, though:

```
Fatal error:  require_once(): Failed opening required '/var/www/kirby_example/site/plugins/uniform/lib/uniform.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/kirby_example/site/plugins/uniform/uniform.php on line 7
PHP Stack trace:
1. {main}() /var/www/kirby_example/index.php:0
2. Kirby->launch() /var/www/kirby_example/index.php:16
3. Kirby->plugins() /var/www/kirby_example/kirby/kirby.php:719
4. Kirby->plugin($name = *uninitialized*, $mode = *uninitialized*) /var/www/kirby_example/kirby/kirby.php:411
5. include_once() /var/www/kirby_example/kirby/kirby.php:438
```

Had to rename lib/UniForm.php to lib/uniform.php to make it work.

Using Ubuntu 14.04. LTS in a VM.

Cheers
MacGyer

**Comment by mzur** [comment]
That's strange since the [case should be correct](https://github.com/mzur/kirby-uniform/blob/9e277945f6bc31c1a7699cfc5be48b07071010d8/uniform/uniform.php#L7) (`UniForm`). Does your file look the same?

**Comment by MacGyer** [comment]
Now you mention it.... that's strange indeed.
Just checked the zip file, everything's fine there. Don't know what went wrong.

Can be closed, sorry for any inconvenience.


Cheers
