### ISSUE TITLE
values not restored if guard fails

### ISSUE THREAD

**Issue by lukehatfield** [mzur/kirby-uniform#72]
Thanks for the plugin! It's working great. Only thing is can't get the value to come back if the guard field doesn't pass. The values do come back if I'm missing a required field, and correctly fill out the guard field. Am I doing something wrong?

**Comment by mzur** [comment]
That's a known problem (#54) and set to be fixed in v2.2. Development is progressing very slowly, though :confused:

**Comment by lukehatfield** [comment]
Got it. I know what you mean about the masters. I'd help if I knew more php. Good luck!
