### ISSUE TITLE
File upload option

### ISSUE THREAD

**Issue by lukehatfield** [mzur/kirby-uniform#73]
Hi Martin, I know you're busy, but any way you could point me in the right direction for adding a **file upload field** to my instance of this plugin? Could it simply being adding a php upload field? Would probably need to add a function to the plugin though, I'm guessing. Thank you.

**Comment by mzur** [comment]
With a custom Uniform action it works exactly as [described in the manual](http://php.net/manual/en/features.file-upload.post-method.php). Only the form field validation (`required` or `validate`) doesn't work with file type input fields because they are not included in the POST data returned by Kirby's `get()` function. This means you have to validate the presence of the form field by yourself in the custom action. Something like this (may not be complete and not secure):

Template:
```html
<form enctype="multipart/form-data" action="<?php echo $page->url()?>#form" method="post">
	<label for="file">File</label>
	<input type="file" name="file" id="file" required/>

	<button type="submit" name="_submit" value="<?php echo $form->token() ?>"<?php e($form->successful(), " disabled")?>>Submit</button>
</form>
```
Controller:
```php
<?php

uniform::$actions['upload'] = function($form, $actionOptions) {
   foreach ($actionOptions['files'] as $field) {
      if (!array_key_exists($field, $_FILES)) {
         return [
            'success' => false,
            'message' => "Field {$field} was not submitted"
         ];
      }
   }

   foreach ($actionOptions['files'] as $field) {
      move_uploaded_file($_FILES[$field]['tmp_name'], $actionOptions['target'].'/'.$_FILES[$field]['name']);
   }

   return [
      'success' => true,
      'message' => "All files uploaded"
   ];
};

return function($site, $pages, $page) {
   $form = uniform('upload-form', [
      'actions' => [[
         '_action' => 'upload',
         'files' => ['file'],
         'target'      => 'content/'.$page->diruri().'/files',
      ]]
   ]);

   return compact('form');
};

```
Be aware that allowing file uploads exposes you to all sorts of security issues. Files with the same name will be overwritten, users could try uploading their own PHP scripts and try executing them, etc. Ideally you should set the filename and not let the user do it (maybe prepend some ID or random string). Also you should disable execution of any scripts in the upload directory. See the manual for [more advice](http://php.net/manual/en/function.move-uploaded-file.php#111412).

**Comment by marianoviola** [comment]
Hi @mzur, I tried your solution but it doesn't work. The `'files' => ['file']` option is returned as string and the `$form` array passed to the custom action never contains the input file fields. I'm using Kirby 2.2.3 and the last version of Uniform grabbed from Github. Any idea?

**Comment by mzur** [comment]
> The 'files' => ['file'] option is returned as string

The code above works for me. How does your action array look like?

> the $form array passed to the custom action never contains the input file fields

That's right. This is the reason why we have to do validation manually for file form fields and I use the `$_FILES` array in my code.

**Comment by marianoviola** [comment]
This is code that contains the upload action:

```php   

return function($site, $pages, $page) {

  $form = uniform('form', 
    array(
      'required' => array(
        'name'  => '',
        'surname'  => '',
        'email' => 'email',
        'phone' => '',
      ),
      'actions' => array(
        array(
          '_action' => 'upload',
          'files' => ['file'],
          'target' => 'content/'.$page->diruri().'/files'
        ),
        array(
          '_action' => 'email',
          'service' => 'html_mailgun',
          'service-options' => array(
            'key'    => c::get('MAILGUN_APY_KEY'),
            'domain' => c::get('MAILGUN_DOMAIN')
          ),
         [...]
       )
     )
   );
  
  return compact('form');

};
```

**Comment by mzur** [comment]
The upload action array looks fine. And the `files` action option is returned as a string, you say? That shouldn't be possible.

**Comment by marianoviola** [comment]
@mzur thank you. Now works, it was my fault.

**Comment by lukehatfield** [comment]
@mzur life-saving. @marianviola your example was very helpful as well.

As you suggested Martin, I renamed the uploaded file. I needed to have the file accessible by the content folder in the Kirby panel, so I added a long hash to the end of the uploaded file for stop-gap security solution. That way panel users can see what was uploaded.

Any guidance/suggestions how I'd send the uploaded file as an attachment to the email? I'm guessing a new custom action would be a place to start, although I think I need custom headers as well. I found this [SE post] (http://stackoverflow.com/questions/826265/simple-php-form-attachment-to-email-code-golf text).

**Comment by mzur** [comment]
@lukehatfield I believe the simplest way is implementing a new email [_service_](https://github.com/getkirby/toolkit/blob/8cc15584a2de848de3a495e997d01740210337a9/lib/email.php#L146-L166) (no action) that uses a fully featured library like [Swift Mailer](http://swiftmailer.org/). With Swift Mailer creating emails with custom headers and attachments is [very easy](http://swiftmailer.org/docs/messages.html). Of course you somehow have to tell the service which files to attach. Maybe it works for you using the [`service-options`](https://github.com/mzur/kirby-uniform/wiki/Action:-Email#service-options) of the email action or maybe you have to extend the email action itself.

**Comment by lukehatfield** [comment]
Once again, excellent help! I may try using [Mandrill] (https://www.mandrill.com/) as I already know them a bit. 

Another thing I thought of is since I'm storing the upload on a server with a long hash appended, if I could just get that file location to the message body, I could send it as a link. Seems a super clean that way, and more sharable.

**Comment by lukehatfield** [comment]
Not to beat a dead horse, but I wanted to let you know I ended up making a new email service like you suggested, incorporating the [phpMailer] (https://github.com/PHPMailer/PHPMailer), inspired by this [Kirby forum thread] (https://forum.getkirby.com/t/send-emails-using-phpmailer/2570). I was able to find the file in the new service plugin using the default $_FILES[$field]['tmp_name'], after setting $field to the name of the input tag. Thanks again!

**Comment by lukehatfield** [comment]
Last question: how can I pass the value of my 'first_name' field along as a service option? I'm using it to build a new file name for the uploaded file.

**Comment by mzur** [comment]
You can use `get('first_name')` in the controller. Make sure to sanitize the filename (by using a character whitelist). There [are](https://en.wikipedia.org/wiki/Directory_traversal_attack) [nasty](https://www.defensecode.com/public/DefenseCode_Unix_WildCards_Gone_Wild.txt) [things](http://www.golemtechnologies.com/articles/shell-injection) that can be done with filenames.

**Comment by lukehatfield** [comment]
Wonderful! Thanks for the code and the tip! Us new guys need it :)

**Comment by illycz** [comment]
Hi @mzur, I tried your solution. Form was sended, but files werent uploaded.

Alert message: Field file was not submitted Thank you, the form was sent successfully.
My controller code:

`
uniform::$actions['upload'] = function($form, $actionOptions) {
   foreach ($actionOptions['files'] as $field) {
      if (!array_key_exists($field, $_FILES)) {
         return [
            'success' => false,
            'message' => "Field {$field} was not submitted"
         ];
      }
   }

   foreach ($actionOptions['files'] as $field) {
      move_uploaded_file($_FILES[$field]['tmp_name'], $actionOptions['target'].'/'.$_FILES[$field]['name']);
   }

   return [
      'success' => true,
      'message' => "All files uploaded"
   ];
};

return function($site, $pages, $page) {
    $form = uniform('contact-form', [
        'required' => [
            'name'  => '',
            '_from' => 'email'
        ],
        'actions' => [
            [
                '_action' => 'upload',
                'files' => ['file'],
                'target' => 'content/'.$page->diruri().'/files',
            ],
            [
                '_action' => 'email',
                'to'      => 'patrik.illy@gmail.com',
                'sender'  => 'patrik.illy@gmail.com',
                'subject' => 'New message from the contact form'
            ]
        ]
    ]);

    return compact('form');
};
`

I tested locally. Any suggestion?

Thanks

Patrik

**Comment by mzur** [comment]
> Field file was not submitted

@illycz Does your file upload field have the name `file`? What are the contents of the `$_FILES` array when the form is submitted?

**Comment by illycz** [comment]
```
array(0) { }
```

:(

I don't know why...

**Comment by illycz** [comment]
My fault, I forgot: enctype="multipart/form-data".
Can you help me within file input validation (size and type)? How can I include that to uniform messages?

Thank a lot

**Comment by mzur** [comment]
> Can you help me within file input validation (size and type)? How can I include that to uniform messages?

Let's open a new issue for that :wink:

**Comment by rppld** [comment]
Currently looking into making this work with v3 of Uniform. @mzur can you maybe give me some hints to what the best approach for this is? I assume you create a separate file for the upload action in `site/plugins` and then chain it in the controller?

**Comment by mzur** [comment]
> I assume you create a separate file for the upload action in site/plugins and then chain it in the controller?

Right, you can take [this](https://github.com/mzur/kirby-uniform/issues/112#issuecomment-269385742) as an example.

**Comment by rppld** [comment]
@mzur Ah thanks, I've overlooked this one! Will give it a try.

**Comment by mzur** [comment]
You're welcome. You can send a PR to help with #113 if you want :wink:

**Comment by thykes** [comment]
Hello! First, i'm a designer with little PHP knowledge but I'm also using Kirby, and I'm trying to attach an image to an email and send it. I'm using code from another [GitHub user](https://gist.github.com/thykes/f6359a7241aa5eb12e05408a42b2a12e) that sends and email with in Kirby but I can't find away to add an attachment and send. I don't know what to do to get it to work using the code here.

**Comment by mzur** [comment]
Hi @thykes, please ask this question in the [forum](https://forum.getkirby.com/) as it doesn't have anything to do with the Uniform plugin.

Hint: You need a library like PHPMailer to [send emails with attachment](https://forum.getkirby.com/t/send-emails-using-phpmailer/2570) in an easy way.
