### ISSUE TITLE
Can't use `_from` for `to`

### ISSUE THREAD

**Issue by creichel** [mzur/kirby-uniform#76]
Hi there,

I'm working with the awesome Kirby uniform plugin and want to send a customized copy (with a customized snippet) to the sender (a.k.a. `_from`) of the form. Therefore I thought this would work:

```
'_action' => 'email',
'to'      => '{_from}',
...
```

But that doesn't work. It throws the error "Invalid recipient" when try to send a form.
Any solution for that?

**Comment by mzur** [comment]
```php
'to' => get('_from'),
```
Should work since all form field values are just POST parameters.

**Comment by creichel** [comment]
Gosh... jup, works. Thank you :-)
