### ISSUE TITLE
A Fatal Error is being occurring in if condition a method is returning value 

### ISSUE THREAD

**Issue by aashishsonawane** [mzur/kirby-uniform#78]
We are trying to set contact form in our Website. The code works well on local server, but when we try to execute the same code files on a server we receive a fatal error notification;

Fatal error: Can't use method return value in write context in /site/plugins/uniform/guards/honeypot.php on line 16

### Possible solution
So after a bit of error debugging we concluded that error is being occured because in '/site/plugins/uniform/guards/honeypot.php on line 16' file,

the code looks like:

if (!empty($form->value($field))) {
        return [
            'success' => false,
            'message' => l::get('uniform-filled-potty'),
        ];
    }

/*
Here: a method is used to check input values, instead if we store input values in a variable & add that variable to check an empty value in if condition probably solved the issue.
So ideally the code should be;
*/

    $form_values = $form->value($field);
    if (!empty($form_values)){
        return [
            'success' => false,
            'message' => l::get('uniform-filled-potty'),
        ];
    }
	
This solves our issue. 

Please suggest for any other feasible solution we have to address the fatal error.

**Comment by mzur** [comment]
What PHP version do you use? These kind of error occurs with PHP versions below 5.5. Instead of fixing the error as you said above (although that works), you really should update your PHP version to 5.6 or 7.0.

That said, while googling for that kind of error I learned that `empty` [shouldn't be used like that](http://stackoverflow.com/a/4328049/1796523). I'll label this issue as a bug and will fix this soon.

**Comment by aashishsonawane** [comment]
Thank you for a reply.

Php version yes true even I figured out that myself. But thought of raising the issue because someone else might face the same issue.

So looking forward for an update over the issue. 

Thanks

**Comment by mzur** [comment]
I've already pushed an update. [v2.2.4](https://github.com/mzur/kirby-uniform/releases/tag/v2.2.4) should work fine for you.

**Comment by aashishsonawane** [comment]
Yes thanks, now the code works fine, good that was a quick update.

Thanks for your support.
