### ISSUE TITLE
How to send form via Google?

### ISSUE THREAD

**Issue by loasca** [mzur/kirby-uniform#79]
Hi,
similar to what requested in #61, how can I add Google as an email service to use with Uniform?
How do I know what the service-options are?
Thanks

**Comment by mzur** [comment]
Unfortunately the Kirby Toolkit does not have a Google email service. How does it work with Google, does it have an API or do you send the emails using your SMTP credentials?

**Comment by loasca** [comment]
Unfortunately I don't know. I only see that it fails sending the messages through. Even contacting the Google Apps support didn't help.

**Comment by mzur** [comment]
It will probably work with your SMTP credentials. Try setting up a new email service with a mailing library like PHPMailer (described [here](https://forum.getkirby.com/t/send-emails-using-phpmailer/2570)). Then [set it up](http://phpmailer.worxware.com/?pg=examplebsmtp) to use your Google SMTP credentials.

**Comment by mzur** [comment]
If you don't know where to begin, open a new thread in the [forum](https://forum.getkirby.com/). There are lots of people happy to help with such things :wink:

**Comment by loasca** [comment]
Will do. Thanks!
