### ISSUE TITLE
Auto reply

### ISSUE THREAD

**Issue by krisak** [mzur/kirby-uniform#81]
Hi, i am probably missing something obvious but i cant figure it out.

I need to update form that is already working and sending data from the visitors to my email. I would like to send them automatic reply with text from panel which i define lets say in $site. I figured that best thing would be make another action because i need to send second email. I dont know however how to send to visitor email (email which i take from the form).

So how do i get the data from the form? I tried to set 'to' as '_from' because i thought the underscored values are the ones gathered from the form on page but it doesnot work.
> 	        'actions' => array(
	            array(
	                '_action' => 'email',
	                'to'      => (string)$site->formrecipient(),
	                'sender'  => (string)$site->formsender(),
	                'subject' => 'Contact',
	                'snippet' => 'uniform-email-contact'
	            ),
	           	array(
	                '_action' => 'email',
	                'to'      => '_from',
	                'sender'  => (string)$site->formsender(),
	                'subject' => 'Thanks for visit',
	                'snippet' => 'uniform-email-visitorreply'
	            ),
	            array(
				   '_action' => 'log',
				   'file'    => './logs/contactmessages.log'
				),
	        )

Thank you for help

**Comment by krisak** [comment]
$form['_from'] -wont work
a::get($form, '_from') - wont work
how do i get the value from the form?

Thaaanks

**Comment by mzur** [comment]
You can use `get('_from')`.

**Comment by krisak** [comment]
Sorry i couldnt find it. 
I have another newbie question. 
Is there a way to see $site in email snippet? Or should i pass the individual values?

**Comment by mzur** [comment]
No problem :wink: 

You can use the `site()` and `page()` [helper functions](https://getkirby.com/docs/cheatsheet#helpers) in the email snippet.

**Comment by krisak** [comment]
Yes it works. Thanks!
