### ISSUE TITLE
[Feature Request] Please Be Compatible with The Official Kirby CLI

### ISSUE THREAD

**Issue by luxlogica** [mzur/kirby-uniform#82]
Please provide support for the official **[Kirby CLI](http://github.com/getkirby/cli)**, an amazing tool that allows power users to instal, update and manage kirby sites - and their plugins - through the command-line.

You can view the [official announcement](https://forum.getkirby.com/t/introducing-the-kirby-cli/) by Bastian on the Kirby Forum, [here](https://forum.getkirby.com/t/introducing-the-kirby-cli/).

**Comment by mzur** [comment]
Although I've added this to the next milestone I'm not really excited about the Kirby CLI re-implementing stuff that is usually done with Composer (and what Composer is really good at) in PHP land. I'm not talking about the other features of the CLI, which are pretty neat, only the package/plugin management part. Introducing the Kirby plugin repository here on GitHub is also duplicating what has already been done with Packagist and a `package.json` belongs to NPM and a Node project, PHP projects use a `composer.json`.

Anyway, just ranting away a little... It's not my decision to make and Bastian sometimes likes to reinvent the wheel :wink: As there are not a lot of changes required to make the plugin compatible with the CLI, I'll probably do this in the next couple of days (but as always pull requests are welcome, too).

**Comment by chbach** [comment]
I have to agree with @mzur here. I’m not too keen on using the kirby cli for plugins – if you wanted to include a gulpfile and package.json for asset compilation in a larger plugin, you would get into conflicts or have two package.json files in separate folders.

**Comment by luxlogica** [comment]
Composer requires a substantial amount of time to learn and implement well. The Kirby CLI allows users to access the functions that are most useful in a Kirby developer's setup, without having to understand the underlying mechanisms of Composer or git. It *is* a great help - and as mentioned above, it's easy to provide that support (often only requiring you to add a single line to your package.json file).
