### ISSUE TITLE
No succes message on submit multiple actions

### ISSUE THREAD

**Issue by tijngoessaert** [mzur/kirby-uniform#86]
Hi, I am using uniform to send a form to multiple recipients with ajax. The mails get send correctly but you don't get a succes message on the frontend, when I send to only one recipient the succes message is show. What could be the problem here? I am using a copy of the code found here: https://blog.the-inspired-ones.de/ajax-uniform

**Comment by mzur** [comment]
Is your code identical to the one shown in the tutorial? What does the JSON response look like if you inspect it in the developer tools of your browser?

**Comment by mzur** [comment]
Take a look at [this comment](https://blog.the-inspired-ones.de/ajax-uniform#comment-2609265628) which addresses a problem that fits your description very well. The cause are the [newlines](https://github.com/mzur/kirby-uniform/blob/f139a44cb49e5ab505c3134698c7fa2dcf4cda8a/uniform/lib/UniForm.php#L491) that will produce invalid JSON.

**Comment by tijngoessaert** [comment]
That did the trick! thanks a lot! 
The code you suggested here did not work for me, but the one in the comment did.
`<?php echo json_encode(explode("\n", trim($form->message()))) ?>`
