### ISSUE TITLE
Distinguish between empty and invalid fields

### ISSUE THREAD

**Issue by mzur** [mzur/kirby-uniform#87]
Implement a more fine grained validation system. Add an option to check if a field `isEmpty()` and if a field `isInvalid()` if the validation failed for a required field. Also add an `isErronous()` function as an alias to `hasError()`. The latter returns `true` if a required field is either empty or invalid.

**Comment by LeBenLeBen** [comment]
Hello!

Was this done at some point? I came across #63 since I was confused by the validation system which only return the error on the first field and not the others. I was wondering if there was a way to change that and display errors for all the fields all the time.

**Comment by mzur** [comment]
I presume you are using Uniform v2.3? This was only implemented for Uniform v3, I recommend to use this version.

**Comment by LeBenLeBen** [comment]
I’m using 3.0.1. At the moment I use `$form->error('fieldname')` to grab errors but only the first field of each rule gets validated.

Here are my form rules:

```php
   $form = new Form([
      'recipient' => [
         'rules' => ['required'],
         'message' => l::get('contact.validate.required'),
      ],
      'name' => [
         'rules' => ['required'],
         'message' => l::get('contact.validate.required'),
      ],
      'email' => [
         'rules' => ['required', 'email'],
         'message' => l::get('contact.validate.email'),
      ],
      'message' => [
         'rules' => ['required'],
         'message' => l::get('contact.validate.required'),
      ],
   ]);
```

And a screenshot when I submit with nothing:

![capture d ecran 2017-04-20 a 17 41 14](https://cloud.githubusercontent.com/assets/793344/25239589/af1b05e0-25f0-11e7-91d9-e122d8fce328.png)

Only once the first field is filled, the second gets the error:

![capture d ecran 2017-04-20 a 17 42 18](https://cloud.githubusercontent.com/assets/793344/25239621/c4a7d87a-25f0-11e7-8d72-27fde37de585.png)

**Comment by mzur** [comment]
That looks like a bug. Let's continue in #128.
