### ISSUE TITLE
Support illuminate/validation

### ISSUE THREAD

**Issue by mzur** [mzur/kirby-uniform#88]
Maybe implement validation functions similar to the ones of [Laravel](https://laravel.com/docs/5.1/validation#available-validation-rules)? Alternatively check if the toolkit validation functions could be extended to support expressions like:

``` php
'email' => 'email',
'eula' => 'accepted',
'password' => 'min:8|confirmed',
'password_confirmation' => 'min:8',
```

**Comment by mzur** [comment]
Alternatively use the (new??) [`invalid`](https://getkirby.com/docs/cheatsheet/helpers/invalid) kirby helper.

**Comment by jevets** [comment]
Just FYI, Laravel 5.3 includes some improvements to validation, allowing for some fluent expressions in `Rule`s. Just something to keep in mind as you're considering expressions.

```php
Validator::make($data, [
    'email' => [
        'required',
        Rule::unique('users')->ignore($user->id),
    ],
]);
```

https://laracasts.com/series/whats-new-in-laravel-5-3/episodes/18
https://laravel.com/docs/5.3/validation

**Comment by mzur** [comment]
Yeah, it doesn't really get better than Laravel's validator. Since Uniform v3 will be properly set up with Composer I've thought about using Kirby's `invalid` by default and optionally support [illuminate/validation](https://github.com/illuminate/validation) as well. This way we don't need to reinvent the wheel for this.

**Comment by mzur** [comment]
I've also thought about proposing an improvement to `invalid` where an error message per validation rule can be configured so better error messages are possible.

**Comment by mzur** [comment]
The improved invalid helper has been merged. I think that should be enough for most use cases.
