### ISSUE TITLE
Allow passing of additional context information / params to email action

### ISSUE THREAD

**Issue by getu-lar** [mzur/kirby-uniform#90]
The use case is pretty simple: I would like to have access to additional PHP objects in my mail template without having to add each individual value as a hidden form field. An example for this would be an event registration form where the user enters his contact information and submits the form; the email should also contain information about the event the user registered for.

A similar concept already exists in the webhook action where the 'params' action options are merged together with the form values thereby allowing the Kirby developer to send additional context information with the webhook invocation.

I propose a very similar mechanism for the email action and I will create a pull-request with my suggested implementation before the end of the week.

**Comment by mzur** [comment]
You can use the `page()`, `pages()` and `site()` [helpers](https://getkirby.com/docs/cheatsheet#helpers) in the email templates, did you think of these? The helpers allow you to access pretty much any information from any page you want.

**Comment by getu-lar** [comment]
Hey

I have thought of these, the problem is:
1. I want to access a specific page for which I need to pass the URI
2. I don't want to do this in the template because that's what controllers are for

Basically I want to keep the details of how the data is passed to the page containing the form and the data retrieval completely separate from the email template.

**Comment by mzur** [comment]
Alright, I'm persuaded :wink:

**Comment by getu-lar** [comment]
See pull-request #91 
I hope I'm not being a bully and I actually convinced you that it is a reasonable thing to do.

**Comment by mzur** [comment]
No, it's fine. Keeping controller code separated from the template is a valid point.

**Comment by getu-lar** [comment]
For me, this just was the fastest reaction and merge on an open source project _ever_! Thanks a lot and keep up the awesome work. I'll check out some of the open issues next week and try to contribute some more.
