### ISSUE TITLE
Caching & AJAX-Form

### ISSUE THREAD

**Issue by jensfranke** [mzur/kirby-uniform#94]
I would like to discuss the best approach for having cached pages and the ajax-form. After activating the cache all requests to the api with the uniform-functions didn't work anymore.

So what do you think about a second api-call (snippet from my custom router):

```
[
        'method' => 'GET',
        'pattern' => $prefix.'/mailchimp-form-token',
        'action' => function () {

            return response::json([
                'token' => uniform('newsletter-form')->token()
            ]);

        },
    ],
```

and in JS I write the returned token to the hidden submit-field. Similar to https://github.com/mzur/kirby-uniform/issues/89

Looking forward to hearing your opinion.

**Comment by mzur** [comment]
I don't quite understand the problem yet. Does the route "endpoint" that accepts the form requests stops working when the cache is enabled? Have you added a cache exception rule for this route?

**Comment by jensfranke** [comment]
The page where the form is embed is cached and I didn't add any cache exception rule to the form-api, because at the moment I don't think it is the problem.

The problem is only the first submit. After the first submit I return the current token in this way:

```
return response::json([
   'success' => $form->successful(),
   'message' => $form->message(),
   'errors' => $errors,
   'token' => $form->token(),
]);
```

and it works. So my idea was to request the current token before the first submit with an extra api-call:

```
[
        'method' => 'GET',
        'pattern' => $prefix.'/mailchimp-form-token',
        'action' => function () {

            return response::json([
                'token' => uniform('newsletter-form')->token()
            ]);

        },
    ],
```

Not a good idea?

**Comment by mzur** [comment]
Ah, now I get it. This should be totally fine :wink:

**Comment by jensfranke** [comment]
Hmm, but it didn't work.

Can you please check the following two api functions?

Thanks in advance!

```
    [
        'method' => 'POST',
        'pattern' => $prefix.'/mailchimp-form/(:any)',
        'action' => function ($key) {

            if (!kirby()->request()->ajax()) return site()->errorPage();

            $newsletter = uniform('newsletter-form', [
                'required' => [
                     '_from' => 'email'
                ],
                'actions' => [
                    [
                        '_action' => 'mailchimp',
                        'api_key' => 'xxx',
                        'list_id' => 'xxx',
                    ]
                ]
            ]);

            // get the names of all erroneous fields
            $errors = array_keys(array_filter(get(), function ($field) use ($newsletter) {
                return $newsletter->hasError($field);
            }, ARRAY_FILTER_USE_KEY));

            // TODO: clean last temp vars
            return response::json([
                'success' => $newsletter->successful(),
                'message' => $newsletter->message(),
                'errors' => $errors,
                'token' => $newsletter->token()
            ]);

        },
    ],
    [
        'method' => 'GET',
        'pattern' => $prefix.'/mailchimp-form-token/(:any)',
        'action' => function ($key) {

            if (!kirby()->request()->ajax()) return site()->errorPage();
            return response::json([
                'token' => uniform('newsletter-form')->token()
            ]);

        },
    ],
```

**Comment by jensfranke** [comment]
If you close your browser and open it again you can reproduce the problem. Maybe the missing »Request Cookie« is the problem? So a topic for the session handling in kirby?

**Comment by mzur** [comment]
What exactly doesn't work? Does it throw an error? Does it return the wrong token?

**Comment by jensfranke** [comment]
I'm still trying to find the bug. At the moment I also add both api-calls to `cache.ignore`, but sometimes for the first request I get: 

```
success: false
error: []
```

**Comment by jensfranke** [comment]
Additional note: It looks like the problem only happen if there are two uniforms (both with a unique-id) on the page.

**Comment by jensfranke** [comment]
Shit, maybe it works with this [approach](https://github.com/mzur/kirby-uniform/issues/94#issuecomment-221027954) and the current problems are only related to my test-workflow. I kill chrome, open chrome again, request the page, open dev tools. Maybe with bad timing the session is killed between retrieving the token and sending the token again?

**Comment by jensfranke** [comment]
Sorry, for messing up the thread, but now I found the problem.

From time to time after restarting chrome or firefox the the stored token is not available:
https://github.com/mzur/kirby-uniform/blob/master/uniform/lib/UniForm.php#L119

**Comment by mzur** [comment]
So were you able to resolve the problem?

**Comment by jensfranke** [comment]
No.

Two calls which fired immediately after DOMContentLoaded use different session-ids. After the call for the second uniform the session-id is renewed and so the token for uniform #1 is invalid.

**Comment by mzur** [comment]
Is the `kirby_session` Cookie sent along correctly? The session shouldn't change if the same cookie was used.

**Comment by jensfranke** [comment]
How can I send the `kirby_session` to uniform?

**Comment by mzur** [comment]
It _should_ be sent automatically but you can check it by examining the `Cookie` header fields of the requests. Both requests should use the same cookie and it should be the same in the `Set-Cookie` response header as well.

**Comment by jensfranke** [comment]
New start of chrome and the first two requests:

![bildschirmfoto 2016-05-24 um 18 45 49](https://cloud.githubusercontent.com/assets/595504/15512406/0899f394-21e0-11e6-9fc9-7fac0b90d0c2.png)
![bildschirmfoto 2016-05-24 um 18 45 56](https://cloud.githubusercontent.com/assets/595504/15512407/089aca62-21e0-11e6-949c-218bd9d70c31.png)

after reload:
![bildschirmfoto 2016-05-24 um 18 48 24](https://cloud.githubusercontent.com/assets/595504/15512422/23a18c74-21e0-11e6-986d-d48e0adf53bc.png)
![bildschirmfoto 2016-05-24 um 18 48 31](https://cloud.githubusercontent.com/assets/595504/15512423/23a19098-21e0-11e6-93b0-0316b7646889.png)

**Comment by mzur** [comment]
Do I understand that right that you have _two_ forms on the same page and the two requests we are talking about are the ones retrieving the separate CSRF tokens for the forms (using the route you mentioned in your first post)? Both requests are submitted simultaneously when the page was loaded? What about the initial response of the HTML page, doesn't it have a `Set-Cookie` header?

**Comment by jensfranke** [comment]
> Do I understand that right that you have two forms on the same page and the two requests we are talking about are the ones retrieving the separate CSRF tokens for the forms (using the route you mentioned in your first post)? 

Yes, two forms in a cached page and so I request one token for each form when the page was page loaded and replace the token with js to have valid tokens for the real submit request.

> Both requests are submitted simultaneously when the page was loaded?

Yes

>  What about the initial response of the HTML page, doesn't it have a Set-Cookie header?

No. After reload everything is fine.

**Comment by mzur** [comment]
Try to chain the requests so the second one is submitted only after the first one was returned.

**Comment by ldanielswakman** [comment]
Hi!

I was facing the same problem; contact form element on all pages and don't want to have to disable cache everywhere. I actually thought of the same approach, getting the CSRF token dynamically and inserting it via AJAX, then I found this thread.

@jensfranke did it work in the end? Am I right in thinking I can also implement a custom route like this?
```
    [
        'method' => 'GET',
        'pattern' => $prefix.'/mailchimp-form-token/(:any)',
        'action' => function ($key) {

            if (!kirby()->request()->ajax()) return site()->errorPage();
            return response::json([
                'token' => uniform('newsletter-form')->token()
            ]);

        },
    ],
```

**Comment by mzur** [comment]
@ldanielswakman Do you still use Uniform v2? If you use the newer v3 your route code must be changed.

**Comment by ldanielswakman** [comment]
No I'm just using the master branch from the plugin, as a gitmodule into my project; so that must be v3. And the `package.json` says:
```
   "version": "3.2.1",
```

I was just copy pasting the route from the previous poster. In any case, what would the 'get CSRF token' route look like for v3?

**Comment by mzur** [comment]
With v3 you can simply use the [`csrf()`](https://getkirby.com/docs/cheatsheet/helpers/csrf) helper to get the token.

**Comment by ldanielswakman** [comment]
Okay great that did the trick it seems. Since I can imagine most people will have caching active on the site, wouldn't it be a good idea to add the route logic to the AJAX example?

**Route:** 
```
  [
    'pattern' => 'contactform_gettoken',
    'method' => 'GET',
    'action'  => function() {

      $token = csrf();
      return response::json(['token' => $token]);
    }
  ],
```

**JS:**
```
var token_request = new XMLHttpRequest();
var request_path = 'contactform_gettoken';

token_request.onreadystatechange = function() {
  var token_fields = document.querySelectorAll('form.contact-form input[name="csrf_token"]');

  if(this.status == 200 && this.readyState == 4) {
    var token = JSON.parse(this.response).token;
    for(i = 0; i < token_fields.length; i++) {
      token_fields[i].value = token;
    }
  }
};
token_request.open('GET', request_path);
token_request.send();
```

**Comment by mzur** [comment]
That would make the AJAX example rather long imo. But it can be added to the [answers section](https://kirby-uniform.readthedocs.io/en/latest/answers/). Feel free to make a PR to the docs and we can continue the discussion there.

**Comment by illycz** [comment]
I have implemented Ajax form from your example.
I have enable cache.
I have route for token from Answers section.
I ignore this route within ignore callback like this:

```
'cache' => [
    'pages' => [
        'active' => true,
        'ignore' => function ($page) {
            return $page->slug() === 'gettoken';
        }
    ]
],
```

Do I need something else?
Because I still get `400 Bad Request` with `{"csrf_token":["Your session timed out. Please submit the form again."]}` response.

Thanks

**Comment by mzur** [comment]
Have you checked (in the network tab of the browser developer tools) if all requests are sent correctly and if the response of the `gettoken` endpoint actually contains the CSRF token?

**Comment by illycz** [comment]
When I have disable cache everything works correctly.
And yes `gettoken` return json like this: `{"token":"23acfb9462a77c1876873468dae36bf05acebc6da086890a9d1470469b73bdc2"}`

**Comment by illycz** [comment]
Do I need this js part:
```
var token_request = new XMLHttpRequest();
var request_path = 'gettoken';

token_request.onreadystatechange = function() {
  var token_fields = document.querySelectorAll('form.contact-form input[name="csrf_token"]');

  if (this.status === 200 && this.readyState === 4) {
    var token = JSON.parse(this.response).token;
    for(i = 0; i < token_fields.length; i++) {
      token_fields[i].value = token;
    }
  }
};

token_request.open('GET', request_path);
token_request.send();
```

somehow integrate to existing js logic or everything should work as is?

**Comment by mzur** [comment]
Yes the additional JS code is essential. Otherwise the form will not work if caching is enabled.

**Comment by illycz** [comment]
I asked if I need somehow integrate it to existing ejax form logic or only paste it and call after content is loaded.

**Comment by mzur** [comment]
That wasn't really clear from your wording. The JS needs to be executed on `load`. You might have to update the `querySelectorAll` to fit to your form(s).

**Comment by illycz** [comment]
Sorry, my english is bad.

I fixed relative path from `request_path = 'gettoken';` to `request_path = '/gettoken';`.
On subpages token is not generated because bad request.

Everything works now. Js replace old cached token by new generated by route.

Thanks for your time!
