### ISSUE TITLE
Action that stores data in the user's session

### ISSUE THREAD

**Issue by lord-executor** [mzur/kirby-uniform#95]
In most of the cases where I use uniform I end up redirecting the user to a different page when the form is submitted, but I still want to include some of the submitted data on the target page - usually for personalization along the lines of "Thank you [FirstName] [LastName] for registering...".

To do that I created the quite possibly simplest useful uniform action:

```php
/*
 * Action to store the form data in the user's session under a key given
 * by the action options 'name' value.
 */
uniform::$actions['session-store'] = function ($form, $actionOptions) {
    // get the name of the session variable
    $name = a::get($actionOptions, 'name', 'session-store');

    // put form into session
    s::set($name, $form);

    return [
        'success' => true,
        'message' => l::get('uniform-session-store-success'),
    ];
};
```

I was wondering if I am the only one doing things like that or if that could be a candidate for an additional built-in uniform action. I would of course create a pull request if that is something that fits within the project scope.

**Comment by mzur** [comment]
Sure, send a PR :wink:

**Comment by mzur** [comment]
Any chance on still getting the PR? :smile:

**Comment by lord-executor** [comment]
Well... this is embarrassing. I had my notifications all f-ed up and _completely_ forgot about this. On the bright side, this gave me the chance to look into v3 and port my code forward.
