### ISSUE TITLE
Token expires after ajax call

### ISSUE THREAD

**Issue by tobystokes** [mzur/kirby-uniform#98]
I'm not sure if this is really a bug, more a cautionary tale, but I thought it would be worth reporting to you anyway.

I have a uniform form, working fine.
However, if I perform an ajax request _after_ the initial load, (I'm GET'ting another kirby template of some bigger image previews), then that causes the original token to become outdated, so the form fails.
In a similar way to your fix for #89, I'm resolving it by passing a new token in that ajax request as well. 

Firstly, i just wanted to check that this is the only/best way around this.

Secondly, that the `$form->hasMessage()` Message was blank in this situation, so it's not immediately clear that (or why) the form has not been sent. Would it be possible to get an error message if the token is invalid?

**Comment by mzur** [comment]
The token should not change unless you also call `uniform()` again in the ajax request for the image previews. Is that the case? You shouldn't have to anyway.

And yes, an error message for an invalid token seems like a good idea. Care to make a pull request? The right place to set the error message is probably [here](https://github.com/mzur/kirby-uniform/blob/f139a44cb49e5ab505c3134698c7fa2dcf4cda8a/uniform/lib/UniForm.php#L197).

**Comment by tobystokes** [comment]
Damn, you're right, I was calling `uniform()` in the site controller, therefore getting recalled in the ajax requests. Put it in the right page controller, and the other requests don't break the token.

(I did have a look at adding the error code there, but couldn't see how to only show it only after submit, not in it's default state. And it would probably require a new translation string as well... )
